// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/dom-construct dojo/query dijit/_WidgetBase dijit/_TemplatedMixin jimu/dijit/ViewStack jimu/utils".split(" "),function(p,k,q,f,m,e,l,r,t,u,n){return p([r,t],{baseClass:"jimu-header-more-popup",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"pages" data-dojo-attach-point\x3d"pagesNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"points jimu-corner-bottom"\x3e\x3cdiv class\x3d"points-inner"data-dojo-attach-point\x3d"pointsNode"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
margin:4,postCreate:function(){this.nodes=[];this.pages=[];this.createCloseBtn()},startup:function(){this.viewStack=new u({views:[],viewType:"dom"},this.pagesNode);this.viewStack.startup();this.resize()},resize:function(){var a=this._calculateGridParam(),d;null!==a?(f.setStyle(this.domNode,n.getPositionStyle(a.position)),this.nodeWidth=a.cellSize-this.margin,this.oldGridParam&&this.oldGridParam.rows===a.rows&&this.oldGridParam.cols===a.cols||(this.clearPages(),this.createPages(a)),this.nodes.forEach(k.hitch(this,
function(c,b){this.setItemNodePosition(c,b,a)})),this.oldGridParam=a,d=l("div.close",this.domNode)[0],f.setStyle(d,{width:.25*this.nodeWidth+"px",height:.25*this.nodeWidth+"px"})):(this.oldGridParam=null,f.setStyle(this.domNode,n.getPositionStyle({left:0,top:0,width:0,height:0,zIndex:111})),this.nodeWidth=0)},setItemNodePosition:function(a,d,c){var b,g,h=48,e=16;b=0===d%c.cols?0:this.margin/2;g=d%(c.rows*c.cols)<c.cols?0:this.margin/2;d={};"number"===typeof this.nodeWidth&&(d.width=this.nodeWidth+
"px",d.height=this.nodeWidth+"px");"number"===typeof b&&(window.isRTL?d.marginRight=b+"px":d.marginLeft=b+"px");"number"===typeof g&&(d.marginTop=g+"px");if(b=l("img",a)[0])c.iconScaled&&(h*=this.nodeWidth/120),f.setStyle(b,{width:h+"px",height:h+"px"});if(h=l("div.node-label",a)[0])c.showLabel?(c.iconScaled&&(e*=this.nodeWidth/120),f.setStyle(h,{"font-size":e+"px",display:"block"})):f.setStyle(h,{"font-size":e+"px",display:"none"});f.setStyle(a,d)},clearPages:function(){q.forEach(this.pages,function(a){this.viewStack.removeView(a.pageNode)},
this);e.empty(this.pointsNode);this.pages=[];this.nodes=[]},createPages:function(a){var d,c,b,g;d=Math.ceil(this.items.length/(a.rows*a.cols));for(c=0;c<d;c++)b=e.create("div",{"class":"page"}),this.createPageItems(c,b,a),this.viewStack.addView(b),1<d&&(g=e.create("div",{"class":"point"},this.pointsNode),this.own(m(g,"click",k.hitch(this,this._onPageNodeClick,c)))),this.pages.push({pageNode:b,pointNode:g});0<this.viewStack.views.length&&this._selectPage(0)},_onPageNodeClick:function(a){this._selectPage(a)},
_selectPage:function(a){1<this.pages.length&&(l(".point",this.domNode).removeClass("point-selected"),f.addClass(this.pages[a].pointNode,"point-selected"));this.viewStack.switchView(this.pages[a].pageNode)},createPageItems:function(a,d,c){var b,g,e;b=this.items.length;g=c.rows*c.cols;c=(a+1)*g;e=c-b;c=Math.min(c,b);for(a*=g;a<c;a++)this.createItemNode(a,d);for(a=b;a<b+e;a++)this.createEmptyItemNode(d)},createItemNode:function(a,d){var c,b;b=this.items[a];c=e.create("div",{"class":"icon-node jimu-float-leading jimu-main-background",
title:b.label,settingId:b.id,"data-widget-name":b.name},d);e.create("img",{src:b.icon},c);e.create("div",{"class":"node-label",title:b.label,innerHTML:n.stripHTML(b.label)},c);c.config=b;this.own(m(c,"click",k.hitch(this,function(){this.onNodeClicked(c)})));this.nodes.push(c)},createEmptyItemNode:function(a){a=e.create("div",{"class":"icon-node jimu-float-leading jimu-main-background"},a);this.nodes.push(a);return a},createCloseBtn:function(){var a;a=e.create("div",{"class":"close"},this.domNode);
e.create("div",{"class":"close-inner jimu-main-background"},a);m(a,"click",k.hitch(this,function(){this.hide()}));return a},hide:function(){f.setStyle(this.domNode,"display","none")},show:function(){f.setStyle(this.domNode,"display","block")},onNodeClicked:function(a){this.hide()},_calculateGridParam:function(){var a,d,c,b,e=!1,h=!0;a=f.getContentBox(jimuConfig.mapId);d=Math.min(a.w,a.h)-40;if(360<=d)b=120;else{b=Math.floor(d/3);if(10>b)return null;e=!0;80>b&&(h=!1)}d=Math.floor((a.h-40)/b);c=Math.floor((a.w-
40)/b);d=4<d?4:d;d=3>d?3:d;c=3>d?3:4<c?4:c;return{rows:d,cols:c,cellSize:b,iconScaled:e,showLabel:h,position:{top:(a.h-b*d)/2,bottom:(a.h-b*d)/2,left:(a.w-b*c)/2,right:(a.w-b*c)/2,width:b*c-this.margin*(c-1)/2,height:b*d-this.margin*(d-1)/2,zIndex:111}}}})});