// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/DeferredList dojo/_base/array esri/request esri/geometry/webMercatorUtils esri/geometry/Polygon esri/geometry/Point esri/geometry/Multipoint esri/geometry/Polyline jimu/utils jimu/portalUtils jimu/portalUrlUtils jimu/tokenUtils jimu/dijit/Message ./CSVUtils".split(" "),function(C,l,n,r,z,D,E,F,L,M,G,q,H,I,p,J,K){return C("SnapShot",null,{portal:null,portalUrl:"",baseName:"",logo:"",originMapId:"",originAppId:"",credential:null,nls:null,
layerArray:[],parent:null,downloadAll:!1,time:null,constructor:function(a){this.parent=a;this.mapItemInfo=this.parent.map.itemInfo;this.extent=this.parent.map.extent;this.nls=l.mixin(this.parent.nls,window.jimuNls.drawBox);this.downloadAll=this.parent.config.csvAllFields;a=a.appConfig;this.portalUrl=a.portalUrl;this.portal=H.getPortal(this.portalUrl);this.selfUrl=I.getPortalSelfInfoUrl(this.portalUrl);this.baseUrl=this.portalUrl+"sharing/rest/";this.logo=a.logo;this.originMapId=a.map.itemId;this.originAppId=
a.appId},createSnapShot:function(a){var b=new n;this.baseName=q.stripHTML(a.name);this.layerArray=[];var c=new Date(a.time),e=c.getTimezoneOffset();this.time=q.fieldFormatter.getFormattedDate(c,{dateFormat:"shortDateShortTime"})+" "+this.nls.utc+(0>e?"+"+Math.abs(e)/60:"-"+e/60);this.portal.getUser().then(l.hitch(this,function(f){this.createFolder(f,this.time).then(l.hitch(this,function(d){this.createLayerItems(f,d,a).then(l.hitch(this,function(a){this.addLayers(f,d,a).then(l.hitch(this,function(a){this.createMap(f,
d,a,this.mapItemInfo).then(l.hitch(this,function(a){new J({message:'\x3ca href\x3d"'+(this.portalUrl+"home/webmap/viewer.html?webmap\x3d"+a.id)+'" target\x3d"_blank"\x3e'+(a.success?this.nls.snapshot_complete:this.nls.snapshot_failed)+"\x3c/a\x3e"});b.resolve("success")}),function(a){b.reject(a)})}),function(a){b.reject(a)})}),function(a){b.reject(a)})}),function(a){b.reject(a)})}),function(a){b.reject(a)});return b},createFolder:function(a,b){var c=new n,e={url:this.baseUrl+"content/users/"+a.username+
"/createFolder",content:{f:"json",folderName:this.baseName+"_"+b,title:this.baseName+"_"+b,description:this.baseName+" "+this.nls.snapshot},handleAs:"json",callbackParamName:"callback"};this.isValidCredential()&&(e.content.token=this.credential.token);D(e,{usePost:!0}).then(l.hitch(this,function(a){c.resolve(a)}),l.hitch(this,function(a){c.reject(a)}));return c},createLayerItems:function(a,b,c){var e=new n;a=c.layers;this.buffers=c.buffers;this.incidents=c.incidents;c=[];for(b=0;b<a.length;b++){var f=
!0;a[b].analysisObject&&"undefined"!==typeof a[b].analysisObject.featureCount&&0===a[b].analysisObject.featureCount&&(f=!1);a[b].graphics&&0===a[b].graphics.length&&(f=!1);f&&c.push(this.createItem(a[b],this.incidents,this.buffers,this.time,this.nls,this.baseName))}var d=[];(new r(c)).then(l.hitch(this,function(a){for(var b=0;b<a.length;b++)d.push(a[b][1]);e.resolve(d)}),l.hitch(this,function(a){e.reject(a)}));return e},addLayers:function(a,b,c){for(var e=new n,f=[],d=0;d<c.length;d++)f.push(a.addItem(c[d],
b.folder.id));var k=[];(new r(f)).then(l.hitch(this,function(a){for(var b=0;b<a.length;b++){var d=a[b][1];d.success&&k.push(d.id)}e.resolve(k)}),l.hitch(this,function(a){e.reject(a)}));return e},createItem:function(a,b,c,e,f,d){var k=new n,h={label:a.label,title:a.label+"_"+e,desc:f.snapshot_append+" "+f.of_append+" "+a.type+" "+f.layer_append+" "+a.label+" ("+e+")",name:a.label+" ("+e+")",tags:[d+","+f.snapshot_append]};if(a.layerObject){var g=a.layerObject;d=a.analysisObject;this.layerArray.push({layer:{id:h.title,
label:h.title,opacity:1,visible:!1},label:h.name});var A;g.infoTemplate&&g.infoTemplate.info&&(A=g.infoTemplate.info);h.popupInfo=A;"groupedSummary"===a.type||"summary"===a.type?d.updateForIncident(b,c,null,null,!0,!0,!0).then(l.hitch(this,function(a){a=this.createAnalysisLayerJSON(a,g,f,e,h);k.resolve(a)})):d.updateForIncident(b,"closest"===a.type?this.parent.config.maxDistance:c,null,!0,!0,!0).then(l.hitch(this,function(a){a=this.createAnalysisLayerJSON(a,g,f,e,h);k.resolve(a)}))}else a=this.createIncidentBufferLayerJSON(a.graphics,
f,e,h),k.resolve(a);return k},createAnalysisLayerJSON:function(a,b,c,e,f){var d=a.graphics;(a=a.context._exportToCSV(d,!0))&&a.push({name:c.snapshot_append,alias:c.snapshot_append,type:"esriFieldTypeString"});for(var k=[],h=0;h<d.length;h++){var g=d[h];g.attributes[c.snapshot_append]=e;g.geometry.cache&&(g.geometry.clearCache(),delete g.geometry.cahce);k.push({attributes:g.attributes,geometry:g.geometry})}return{title:f.title,type:"Feature Collection",tags:f.tags,description:f.desc,extent:b.fullExtent,
name:f.title,text:JSON.stringify({layers:[{layerDefinition:{capabilities:"Query",name:f.name,geometryType:b.geometryType,objectIdField:b.objectIdField,type:"Feature Layer",extent:b.fullExtent,drawingInfo:{renderer:b.renderer.toJson()},fields:a},popupInfo:f.popupInfo,featureSet:{features:k,geometryType:b.geometryType}}]}),f:"json"}},createIncidentBufferLayerJSON:function(a,b,c,e){var f=[],d=[],k=[];z.forEach(a,function(a){switch(a.geometry.type){case "point":f.push(a);break;case "polyline":d.push(a);
break;case "polygon":k.push(a)}});a=[];0<k.length&&a.push(k);0<d.length&&a.push(d);0<f.length&&a.push(f);for(var h=[],g={point:"esriGeometryPoint",polyline:"esriGeometryPolyline",polygon:"esriGeometryPolygon"},l={point:this.nls.point,polyline:this.nls.line,polygon:this.nls.polygon},n={xmin:this.extent.xmin,ymin:this.extent.ymin,xmax:this.extent.xmax,ymax:this.extent.ymax,spatialReference:this.extent.spatialReference},y=0;y<a.length;y++){var u=a[y],r;if(0<u.length){var m=u[0];r=l["undefined"!==typeof m.geometry?
m.geometry.type:m.type];for(var v=g["undefined"!==typeof m.geometry?m.geometry.type:m.type],q=m.symbol.toJson(),p=[],w=0;w<u.length;w++){var m=u[w],x;switch(v){case "esriGeometryPolyline":x=m.geometry.paths;break;case "esriGeometryPolygon":x=m.geometry.rings;break;case "esriGeometryPoint":x=[m.geometry]}var B=0,t;z.forEach(x,function(a){switch(v){case "esriGeometryPolyline":t=new G(a);t.spatialReference=m.geometry.spatialReference;break;case "esriGeometryPolygon":t=new F(a);t.spatialReference=m.geometry.spatialReference;
break;case "esriGeometryPoint":t=a}a={attributes:{ObjectID:w+B},geometry:t};a.attributes[b.snapshot_append]=c;p.push(a);B+=1})}h.push({layerDefinition:{capabilities:"Query",name:1===a.length?e.name:r,geometryType:v,objectIdField:"ObjectID",type:"Feature Layer",extent:n,drawingInfo:{renderer:{type:"simple",label:"",description:"",symbol:q}},fields:[{name:"ObjectID",alias:"ObjectID",type:"esriFieldTypeOID"},{name:b.snapshot_append,alias:b.snapshot_append,type:"esriFieldTypeString"}]},featureSet:{features:p,
geometryType:v}})}}this.layerArray.push({layer:{id:e.title,label:e.title,opacity:1,visible:!0},label:e.name});return{title:e.title,type:"Feature Collection",tags:e.tags,description:e.desc,extent:n,name:e.title,text:JSON.stringify({layers:h}),f:"json"}},createMap:function(a,b,c,e){var f=e.itemData;e=this.baseName+" ("+this.nls.snapshot_append+" "+this.time+")";for(var d,k=[],h=0;h<f.baseMap.baseMapLayers.length;h++)d=f.baseMap.baseMapLayers[h],k.push({id:d.id,layerType:d.layerType,url:d.url,visibility:d.visibility,
opacity:d.opacity,title:d.title}),d=d.resourceInfo.spatialReference;f={baseMapLayers:k};k=[];for(h=0;h<this.layerArray.length;h++){var g=this.layerArray[h];k.push({id:g.layer.id,layerType:"ArcGISFeatureLayer",visibility:g.layer.visible,opacity:g.layer.opacity,title:g.label,type:"Feature Collection",itemId:c[h]})}c=E.webMercatorToGeographic(this.extent);c={title:e,type:"Web Map",item:e,extent:c.xmin+","+c.ymin+","+c.xmax+","+c.ymax,text:JSON.stringify({operationalLayers:k,baseMap:f,spatialReference:d,
authoringApp:"WebMapViewer",authoringAppVersion:"4.1",version:"2.4"}),tags:this.baseName+","+this.nls.snapshot_append,wabType:"HTML"};return a.addItem(c,b.folder.id)},_checkCredential:function(){var a=p.isValidCredential(this.credential);a||this.clearCredentialAndUser();return a},isValidCredential:function(){this.updateCredential();return this._checkCredential()},updateCredential:function(){this._checkCredential()||(this.credential=p.getPortalCredential(this.portalUrl))},clearCredentialAndUser:function(){this.user=
this.credential=null},createDownloadZip:function(a,b,c){var e=new n,f=this.nls.calculated_results;this._performAnalysis(a,b,c,this.downloadAll,!1).then(function(a){for(var b=[],d=0;d<a.length;d++){var c=a[d];(c=c.context._exportToCSV(c.graphics,!1,!0,c.analysisResults))&&b.push(c)}0<b.length&&K.exportCalculatedResultsCSV(f,b);e.resolve("success")},function(a){e.reject(a)});return e},_performAnalysis:function(a,b,c,e,f){for(var d=new n,k=[],h=0;h<a.length;h++){var g=a[h];console.log("AO: "+g);var p=
!0;g.analysisObject&&"undefined"!==typeof g.analysisObject.featureCount&&0===g.analysisObject.featureCount&&(p=!1);p&&("groupedSummary"===g.type||"summary"===g.type?k.push(g.analysisObject.updateForIncident(b,c,null,null,!0,f,e)):k.push(g.analysisObject.updateForIncident(b,"closest"===g.type?this.parent.config.maxDistance:c,null,!0,f,e)))}var q=[];(new r(k)).then(l.hitch(this,function(a){for(var b=0;b<a.length;b++)q.push(a[b][1]);d.resolve(q)}),l.hitch(this,function(a){console.error(a);d.reject(a)}));
return d}})});