// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fet",copy:"Kopier",cut:"Klipp ut","delete":"Slett",indent:"Innrykk",insertHorizontalRule:"Vannrett strek",insertOrderedList:"Nummerert liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Midtstill",justifyFull:"Juster",justifyLeft:"Venstrejuster",justifyRight:"H\u00f8yrejuster",outdent:"Fjern innrykk",paste:"Lim inn",redo:"Gj\u00f8r om",removeFormat:"Fjern format",selectAll:"Velg alle",strikethrough:"Gjennomstreking",subscript:"Senket skrift",
superscript:"Hevet skrift",underline:"Understreking",undo:"Angre",unlink:"Fjern kobling",createLink:"Opprett kobling",toggleDir:"Bytt retning",insertImage:"Sett inn bilde",insertTable:"Sett inn/rediger tabell",toggleTableBorder:"Bytt tabellkant",deleteTable:"Slett tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-kilde",foreColor:"Forgrunnsfarge",hiliteColor:"Bakgrunnsfarge",plainFormatBlock:"Avsnittsstil",formatBlock:"Avsnittsstil",fontSize:"Skriftst\u00f8rrelse",fontName:"Skriftnavn",tabIndent:"Tabulatorinnrykk",
fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",viewSource:"Vis HTML-kilde",print:"Skriv ut",newPage:"Ny side",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrift",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasi",noFormat:"Ingen",p:"Avsnitt",
h1:"Overskrift",h2:"Undertittel",h3:"Under-undertittel",pre:"Forh\u00e5ndsformatert",1:"xx-liten",2:"x-liten",3:"liten",4:"middels",5:"stor",6:"x-stor",7:"xx-stor",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Forh\u00e5ndsvis",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8k:",findTooltip:"Skriv inn teksten du vil s\u00f8ke etter",replaceLabel:"Erstatt med:",replaceTooltip:"Skriv inn teksten du vil erstatte med",findReplace:"S\u00f8k og erstatt",matchCase:"Skill mellom store og sm\u00e5 bokstaver",
matchCaseTooltip:"Skill mellom store og sm\u00e5 bokstaver",backwards:"Bakover",backwardsTooltip:"S\u00f8k bakover etter tekst",replaceAllButton:"Erstatt alle",replaceAllButtonTooltip:"Erstatt all tekst",findButton:"S\u00f8k",findButtonTooltip:"S\u00f8k etter teksten",replaceButton:"Erstatt",replaceButtonTooltip:"Erstatt teksten",replaceDialogText:"Erstattet ${0} forekomster.",eofDialogText:"Siste forekomst ${0}",eofDialogTextFind:"funnet",eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lim inn fra Word",
instructions:"Lim inn innhold fra Word til tekstboksen nedenfor. N\u00e5r du er forn\u00f8yd med innholdet du skal sette inn, trykker du p\u00e5 innlimingsknappen. Hvis du vil avbryte innsettingen av teksten, trykker du p\u00e5 avbruddsknappen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Sett inn anker",title:"Ankeregenskaper",anchor:"Navn:",text:"Beskrivelse:",set:"Definer",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokksitat",_localized:{}},
"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Diagraminnstillinger",addNewLabel:"Legg til ny",generalSettingLabel:"Generelle innstillinger",layerChooser:{title:"Velg laget du vil lage diagram av",selectPolygonLayerLabel:"Velg lag",selectPolygonLayerHintText:"Hint: Hvis du konfigurerer flere diagrammer, m\u00e5 lagene ha samme geomertritype",selectRelatedTableLayerLabel:"Velg tabell knyttet til lag",selectRelatedTableLayerHintText:"Hint: Bare tabeller med numeriske felt vises",
errorInSelectingPolygonLayer:"Velg et lag som har et tilknyttet punktlag.",errorInSelectingRelatedLayer:"Velg en gyldig tilknyttet tabell/gyldig lag som det skal opprettes lag for.",polygonLayerNotHavingRelationships:"Det valgte laget har ikke tilknyttet tabell/lag."},ChartSetting:{sectionTitle:"Seksjonstittel",sectionTitleHintText:"Hint: Vises i overskriften for seksjonen",chartTitle:"Diagramtittel",chartTitleHintText:"Hint: Vises i midten \u00f8verst p\u00e5 diagrammet",chartDescription:"Beskrivelse",
chartDescriptionHintText:"Hint: Vises under diagrammet",chartType:"Diagramtype",barChart:"Stolpediagram",pieChart:"Sektordiagram",polarChart:"Polardiagram",dataSeriesField:"Dataseriefelt",labelField:"P\u00e5skriftfelt",chartColor:"Diagramfarge",singleColor:"En farge",colorByTheme:"Farge etter tema",colorByFieldValue:"Farge etter feltverdi",xAxisTitle:"Tittel p\u00e5 X-akse",xAxisHintText:"Hint: Tittelen p\u00e5 X-aksen",yAxisTitle:"Tittel p\u00e5 Y-akse",yAxisHintText:"Hint: Tittelen p\u00e5 Y-aksen",
fieldColorLabel:"Etikett",fieldColorColor:"Farge",defaultFieldSelectLabel:"Velg",errMsgFieldValuesNotFound:"Finner ingen verdier for feltet som er valgt",errMsgSectionTitle:"Skriv inn seksjonstittelen",errMsgFieldByValue:"Velg en feltverdi",settingTabTitle:"Innstilling",layoutTabTitle:"Oppsett",polarChartSelectFieldsHintText:"Hint: Velg felter for \u00e5 generere polardiagram",visibilityText:"Synlighet",fieldNameText:"Feltnavn",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Velg tre eller flere felter for \u00e5 generere polardiagram",
polarChartPolygonFillLabel:"Fyll polygon",polarChartPolygonFillHintText:"Hint: Merk av i boksen for \u00e5 vise polygonfyll i polardiagram",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"\u00d8rken",themeDistinctive:"Distinktiv",themeDollar:"Dollar",themeGrasshopper:"Gresshoppe",themeGrasslands:"Gresslette",themeGreySkies:"GreySkies",themeHarmony:"Harmoni",themeIndigoNation:"IndigoNation",
themeIreland:"Irland",themeMiamiNice:"MiamiNice",themeMinty:"Mint",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Kratt",themeWatersEdge:"WatersEdge",themeWetlandText:"V\u00e5tmark",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Generelle innstillinger",
locationSymbolLabel:"Grafisk symbol for lokasjon",locationSymbolHintText:"Hint: Brukes til \u00e5 vise symbol for adresse og klikket lokasjon",refreshIntervalLabel:"Oppdateringsintervall",refreshIntervalHintText:"Hint: Brukes til \u00e5 oppdatere diagrammer basert p\u00e5 dette intervallet. Angi en verdi mellom 1 tog 1440 minutter.",errMsgRefreshInterval:"Angi et oppdateringsintervall p\u00e5 mellom 0 og 1440 minutter",symbolPickerPreviewText:"Forh\u00e5ndsvisning:"},_localized:{}}});