// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dimensione",fontName:"Carattere",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",
monospace:"spaziatura fissa",cursive:"corsivo",fantasy:"fantasy",noFormat:"Nessuna",p:"Paragrafo",h1:"Intestazione",h2:"Sottointestazione",h3:"Sottointestazione secondaria",pre:"Preformattato",1:"piccolissimo",2:"molto piccolo",3:"piccolo",4:"medio",5:"grande",6:"molto grande",7:"grandissimo",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Anteprima",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Trova:",findTooltip:"Immettere il testo da ricercare",replaceLabel:"Sostituisci con:",
replaceTooltip:"Immettere il testo con cui sostituire",findReplace:"Trova e sostituisci",matchCase:"Corrispondenza maiuscolo/minuscolo",matchCaseTooltip:"Corrispondenza maiuscolo/minuscolo",backwards:"Indietro",backwardsTooltip:"Ricercare il testo all'indietro",replaceAllButton:"Sostituisci tutti",replaceAllButtonTooltip:"Sostituisci tutto il testo",findButton:"Trova",findButtonTooltip:"Trova il testo",replaceButton:"Sostituisci",replaceButtonTooltip:"Sostituisci il testo",replaceDialogText:"Sostituite ${0} ricorrenze.",
eofDialogText:"Ultime ${0} ricorrenze",eofDialogTextFind:"trovato",eofDialogTextReplace:"sostituito",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Incolla da Word",instructions:"Incollare i contenuti da Word nella seguente casella di testo. Quando si \u00e8 deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserisci ancoraggio",
title:"Propriet\u00e0 ancoraggio",anchor:"Nome:",text:"Descrizione:",set:"Imposta",cancel:"Annulla",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Impostazioni grafico",addNewLabel:"Aggiungi nuovo",generalSettingLabel:"Impostazioni generali",layerChooser:{title:"Selezionare layer da rappresentare",selectPolygonLayerLabel:"Seleziona layer",selectPolygonLayerHintText:"Suggerimento: se si configurano pi\u00f9 grafici, il tipo di geometria dei layer deve essere identica",
selectRelatedTableLayerLabel:"Seleziona tabella correlata a layer",selectRelatedTableLayerHintText:"Suggerimento: vengono visualizzate solo le tabelle con campi numerici",errorInSelectingPolygonLayer:"Selezionare un layer con un layer punto correlato.",errorInSelectingRelatedLayer:"Selezionare una tabella/layer correlato valido nel layer.",polygonLayerNotHavingRelationships:"Il layer selezionato non dispone di tabella/layer correlato."},ChartSetting:{sectionTitle:"Titolo sezione",sectionTitleHintText:"Suggerimento: visualizzato nel titolo intestazione sezione",
chartTitle:"Titolo grafico",chartTitleHintText:"Suggerimento: visualizzato al centro nella parte superiore del grafico",chartDescription:"Descrizione",chartDescriptionHintText:"Suggerimento: visualizzato sotto il grafico",chartType:"Tipo di grafico",barChart:"Grafico a barre",pieChart:"Grafico a torta",polarChart:"Grafico polare",dataSeriesField:"Campo serie di dati",labelField:"Campo etichetta",chartColor:"Colore grafico",singleColor:"Colore singolo",colorByTheme:"Colore in base a tema",colorByFieldValue:"Colore in base a valore campo",
xAxisTitle:"Titolo asse X",xAxisHintText:"Suggerimento: titolo asse X",yAxisTitle:"Titolo asse Y",yAxisHintText:"Suggerimento: titolo asse Y",fieldColorLabel:"Etichetta",fieldColorColor:"Colore",defaultFieldSelectLabel:"Seleziona",errMsgFieldValuesNotFound:"Impossibile trovare i valori per il campo selezionato",errMsgSectionTitle:"Immettere i titolo di sezione",errMsgFieldByValue:"Selezionare un valore campo",settingTabTitle:"Impostazione",layoutTabTitle:"Layout",polarChartSelectFieldsHintText:"Suggerimento: selezionare campi per generare grafico polare",
visibilityText:"Visibilit\u00e0",fieldNameText:"Nome campo",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Selezionare tre o pi\u00f9 campi per generare grafico polare",polarChartPolygonFillLabel:"Riempi poligono",polarChartPolygonFillHintText:"Suggerimento: selezionare la casella di controllo per mostrare il riempimento poligono nel grafico polare",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",
themeDesert:"Deserto",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Irlanda",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Terreno paludoso",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",
themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Impostazioni generali",locationSymbolLabel:"Simbolo posizione grafica",locationSymbolHintText:"Suggerimento: utilizzato per visualizzare simbolo per posizione indirizzo e selezione",refreshIntervalLabel:"Intervallo di aggiornamento",refreshIntervalHintText:"Suggerimento: utilizzato per aggiornare i grafici basati su questo intervallo. Specificare un valore compreso tra 1 e 1440 minuti",
errMsgRefreshInterval:"Specificare l'intervallo di aggiornamento compreso tra 0 e 1440 minuti",symbolPickerPreviewText:"Anteprima:"},_localized:{}}});