// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pogrubienie",copy:"Kopiuj",cut:"Wytnij","delete":"Usu\u0144",indent:"Wci\u0119cie",insertHorizontalRule:"Linia pozioma",insertOrderedList:"Lista numerowana",insertUnorderedList:"Lista wypunktowana",italic:"Kursywa",justifyCenter:"Wyr\u00f3wnaj do \u015brodka",justifyFull:"Wyr\u00f3wnaj do lewej i prawej",justifyLeft:"Wyr\u00f3wnaj do lewej",justifyRight:"Wyr\u00f3wnaj do prawej",outdent:"Usu\u0144 wci\u0119cie",paste:"Wklej",redo:"Pon\u00f3w",removeFormat:"Usu\u0144 formatowanie",
selectAll:"Wybierz wszystko",strikethrough:"Przekre\u015blenie",subscript:"Indeks dolny",superscript:"Indeks g\u00f3rny",underline:"Podkre\u015blenie",undo:"Cofnij",unlink:"Usu\u0144 odsy\u0142acz",createLink:"Utw\u00f3rz odsy\u0142acz",toggleDir:"Prze\u0142\u0105cz kierunek",insertImage:"Wstaw obraz",insertTable:"Wstaw/edytuj tabel\u0119",toggleTableBorder:"Prze\u0142\u0105cz ramk\u0119 tabeli",deleteTable:"Usu\u0144 tabel\u0119",tableProp:"W\u0142a\u015bciwo\u015b\u0107 tabeli",htmlToggle:"\u0179r\u00f3d\u0142o HTML",
foreColor:"Kolor pierwszego planu",hiliteColor:"Kolor t\u0142a",plainFormatBlock:"Styl akapitu",formatBlock:"Styl akapitu",fontSize:"Wielko\u015b\u0107 czcionki",fontName:"Nazwa czcionki",tabIndent:"Wci\u0119cie o tabulator",fullScreen:"Prze\u0142\u0105cz pe\u0142ny ekran",viewSource:"Wy\u015bwietl kod \u017ar\u00f3d\u0142owy HTML",print:"Drukuj",newPage:"Nowa strona",systemShortcut:"Dzia\u0142anie ${0} jest dost\u0119pne w tej przegl\u0105darce wy\u0142\u0105cznie przy u\u017cyciu skr\u00f3tu klawiaturowego. Nale\u017cy u\u017cy\u0107 klawiszy ${1}.",
ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Rozmiar",fontName:"Czcionka",formatBlock:"Format",serif:"szeryfowa","sans-serif":"bezszeryfowa",monospace:"czcionka o sta\u0142ej szeroko\u015bci",cursive:"kursywa",fantasy:"fantazyjna",noFormat:"Brak",p:"Akapit",h1:"Nag\u0142\u00f3wek",h2:"Nag\u0142\u00f3wek 2-go poziomu",h3:"Nag\u0142\u00f3wek 3-go poziomu",pre:"Wst\u0119pnie sformatowane",1:"najmniejsza",2:"mniejsza",3:"ma\u0142a",4:"\u015brednia",
5:"du\u017ce",6:"wi\u0119ksza",7:"najwi\u0119ksza",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Podgl\u0105d",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Znajd\u017a:",findTooltip:"Wprowad\u017a szukany tekst",replaceLabel:"Zast\u0105p przez:",replaceTooltip:"Wprowad\u017a tekst zast\u0119puj\u0105cy",findReplace:"Znajd\u017a i zast\u0105p",matchCase:"Uwzgl\u0119dnij wielko\u015b\u0107 liter",matchCaseTooltip:"Uwzgl\u0119dnij wielko\u015b\u0107 liter",backwards:"Do ty\u0142u",
backwardsTooltip:"Wyszukaj tekst wstecz",replaceAllButton:"Zast\u0105p wszystko",replaceAllButtonTooltip:"Zast\u0105p ca\u0142y tekst",findButton:"Znajd\u017a",findButtonTooltip:"Znajd\u017a tekst",replaceButton:"Zast\u0105p",replaceButtonTooltip:"Zast\u0105p tekst",replaceDialogText:"Zast\u0105pione wyst\u0105pienia: ${0}.",eofDialogText:"Ostatnie wyst\u0105pienie: ${0}",eofDialogTextFind:"znaleziono",eofDialogTextReplace:"zast\u0105pione",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Wklej z programu Word",
instructions:"Wklej tekst z programu Word do poni\u017cszego pola tekstowego. Po uzyskaniu odpowiedniej tre\u015bci do wstawienia kliknij przycisk Wklej. Aby przerwa\u0107 wstawianie tre\u015bci, kliknij przycisk Anuluj.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Wstaw zakotwiczenie",title:"W\u0142a\u015bciwo\u015bci zakotwiczenia",anchor:"Nazwa:",text:"Opis:",set:"Ustaw",cancel:"Anuluj",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Cytat blokowy",_localized:{}},
"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Ustawienia diagramu",addNewLabel:"Dodaj nowy",generalSettingLabel:"Ustawienia og\u00f3lne",layerChooser:{title:"Wybierz warstw\u0119 do utworzenia diagramu",selectPolygonLayerLabel:"Zaznacz warstw\u0119",selectPolygonLayerHintText:"Wskaz\u00f3wka: w przypadku konfigurowania wielu diagram\u00f3w warstwy musz\u0105 mie\u0107 ten sam typ geometrii",selectRelatedTableLayerLabel:"Wybierz tabel\u0119 powi\u0105zan\u0105 z warstw\u0105",
selectRelatedTableLayerHintText:"Wskaz\u00f3wka: tylko tabele z polami liczbowymi s\u0105 wy\u015bwietlane",errorInSelectingPolygonLayer:"Wybierz warstw\u0119, kt\u00f3ra ma powi\u0105zan\u0105 warstw\u0119 punktow\u0105.",errorInSelectingRelatedLayer:"Wybierz prawid\u0142ow\u0105 tabel\u0119/warstw\u0119 powi\u0105zan\u0105 z warstw\u0105.",polygonLayerNotHavingRelationships:"Wybrana warstwa nie ma \u017cadnej powi\u0105zanej tabeli/warstwy."},ChartSetting:{sectionTitle:"Tytu\u0142 sekcji",sectionTitleHintText:"Wskaz\u00f3wka: wy\u015bwietlane w tytule nag\u0142\u00f3wka sekcji",
chartTitle:"Tytu\u0142 diagramu",chartTitleHintText:"Wskaz\u00f3wka: wy\u015bwietlane na \u015brodku u g\u00f3ry diagramu",chartDescription:"Opis",chartDescriptionHintText:"Wskaz\u00f3wka: wy\u015bwietlane poni\u017cej diagramu",chartType:"Typ diagramu",barChart:"Diagram s\u0142upkowy grupowy",pieChart:"Diagram ko\u0142owy",polarChart:"Wykres biegunowy",dataSeriesField:"Pole serii danych",labelField:"Pole etykiety",chartColor:"Kolor diagramu",singleColor:"Jeden kolor",colorByTheme:"Kolor wg motywu",
colorByFieldValue:"Kolor wg warto\u015bci pola",xAxisTitle:"Tytu\u0142 osi X",xAxisHintText:"Wskaz\u00f3wka: tytu\u0142 osi X",yAxisTitle:"Tytu\u0142 osi Y",yAxisHintText:"Wskaz\u00f3wka: tytu\u0142 osi Y",fieldColorLabel:"Etykieta",fieldColorColor:"Kolor",defaultFieldSelectLabel:"Zaznacz",errMsgFieldValuesNotFound:"Nie mo\u017cna znale\u017a\u0107 warto\u015bci dla wybranego pola",errMsgSectionTitle:"Podaj tytu\u0142 sekcji",errMsgFieldByValue:"Wybierz warto\u015b\u0107 pola",settingTabTitle:"Ustawienie",
layoutTabTitle:"Kompozycja",polarChartSelectFieldsHintText:"Wskaz\u00f3wka: wybierz pola, aby wygenerowa\u0107 wykres biegunowy",visibilityText:"Widoczno\u015b\u0107",fieldNameText:"Nazwa pola",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Wybierz co najmniej trzy pola, aby wygenerowa\u0107 wykres biegunowy",polarChartPolygonFillLabel:"Wype\u0142nij poligon",polarChartPolygonFillHintText:"Wskaz\u00f3wka: zaznacz pole wyboru, aby wy\u015bwietli\u0107 wype\u0142nienie poligonu na wykresie biegunowym",
ThemeSelector:{themeAdobebricks:"Ceg\u0142y",themeAlgae:"Algi",themeBahamation:"Bahamation",themeBlueDusk:"B\u0142\u0119kitny zmrok",themeCubanShirts:"Kuba\u0144skie koszule",themeDesert:"Pustynia",themeDistinctive:"Kontrasty",themeDollar:"Dolar",themeGrasshopper:"Pasikonik",themeGrasslands:"\u0141\u0105ki",themeGreySkies:"Szare niebo",themeHarmony:"Harmonia",themeIndigoNation:"IndigoNation",themeIreland:"Irlandia",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"Purpurowy deszcz",themeRoyalPurples:"Kr\u00f3lewska purpura",
themeSageToLime:"Sza\u0142wia-limonka",themeTufte:"Tufte",themeWatersEdge:"Lustro wody",themeWetlandText:"Teren podmok\u0142y",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Ustawienia og\u00f3lne",locationSymbolLabel:"Graficzny symbol lokalizacji",locationSymbolHintText:"Wskaz\u00f3wka: s\u0142u\u017cy do wy\u015bwietlania symbolu dla adresu i lokalizacji klikni\u0119cia",
refreshIntervalLabel:"Interwa\u0142 od\u015bwie\u017cania",refreshIntervalHintText:"Wskaz\u00f3wka: s\u0142u\u017cy do od\u015bwie\u017cania diagram\u00f3w zgodnie z tym interwa\u0142em. Okre\u015bl warto\u015b\u0107 z zakresu od 1 do 1440 minut",errMsgRefreshInterval:"Podaj interwa\u0142 od\u015bwie\u017cania z zakresu od 0 do 1440 minut",symbolPickerPreviewText:"Zobacz podgl\u0105d:"},_localized:{}}});