// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Gr\u00f6\u00dfe",fontName:"Schriftart",
formatBlock:"Format",serif:"Serife","sans-serif":"Serifenlos",monospace:"Monospaceschrift",cursive:"Kursiv",fantasy:"Fantasie",noFormat:"Keine Angabe",p:"Absatz",h1:"\u00dcberschrift",h2:"Unter\u00fcberschrift",h3:"Unterunter\u00fcberschrift",pre:"Vorformatiert",1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Vorschau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Suchen:",findTooltip:"Text zum Suchen eingeben",replaceLabel:"Ersetzen durch:",
replaceTooltip:"Text zum Ersetzen eingeben",findReplace:"Suchen und ersetzen",matchCase:"Gro\u00df- und Kleinschreibung abgleichen",matchCaseTooltip:"Gro\u00df- und Kleinschreibung abgleichen",backwards:"Zur\u00fcck",backwardsTooltip:"R\u00fcckw\u00e4rts nach Text suchen",replaceAllButton:"Global ersetzen",replaceAllButtonTooltip:"Gesamten Text ersetzen",findButton:"Suchen",findButtonTooltip:"Text suchen",replaceButton:"Ersetzen",replaceButtonTooltip:"Text ersetzen",replaceDialogText:"${0} Vorkommen ersetzt.",
eofDialogText:"Letztes Vorkommen ${0}",eofDialogTextFind:"gefunden",eofDialogTextReplace:"ersetzt",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Aus Word einf\u00fcgen",instructions:"F\u00fcgt den Inhalt aus Word in das Textfeld unten ein. Wenn Sie mit dem einzuf\u00fcgenden Inhalt zufrieden sind, klicken Sie auf die Schaltfl\u00e4che zum Einf\u00fcgen. Um das Einf\u00fcgen von Text abzubrechen, klicken Sie auf die Schaltfl\u00e4che zum Abbrechen. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker einf\u00fcgen",
title:"Eigenschaften des Ankers",anchor:"Name:",text:"Beschreibung:",set:"Festlegen",cancel:"Abbrechen",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockzitat",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Diagrammeinstellungen",addNewLabel:"Neue hinzuf\u00fcgen",generalSettingLabel:"Allgemeine Einstellungen",layerChooser:{title:"Layer zur Darstellung ausw\u00e4hlen",selectPolygonLayerLabel:"Layer ausw\u00e4hlen",selectPolygonLayerHintText:"Hinweis: Wenn Sie mehrere Diagramme darstellen, m\u00fcssen die Layer denselben Geometrietyp aufweisen",
selectRelatedTableLayerLabel:"Mit Layer in Beziehung stehende Tabelle ausw\u00e4hlen",selectRelatedTableLayerHintText:"Hinweis: Nur Tabellen mit numerischen Feldern k\u00f6nnen angezeigt werden",errorInSelectingPolygonLayer:"W\u00e4hlen Sie einen Layer aus, der einen zugeh\u00f6rigen Punkt-Layer aufweist",errorInSelectingRelatedLayer:"W\u00e4hlen Sie eine(n) g\u00fcltige(n) Tabelle/Layer aus, die/der mit dem Layer in Beziehung steht",polygonLayerNotHavingRelationships:"Der ausgew\u00e4hlte Layer weist keine(n) zugeh\u00f6rige(n) Tabelle/Layer auf."},
ChartSetting:{sectionTitle:"Abschnittstitel",sectionTitleHintText:"Hinweis: Wird in der \u00dcberschrift (im Titel) des Abschnitts angezeigt",chartTitle:"Diagrammtitel",chartTitleHintText:"Hinweis: Wird zentriert \u00fcber dem Diagramm angezeigt",chartDescription:"Beschreibung",chartDescriptionHintText:"Hinweis: Wird unter dem Diagramm angezeigt.",chartType:"Diagrammtyp",barChart:"Balkendiagramm",pieChart:"Kreisdiagramm",polarChart:"Polardiagramm",dataSeriesField:"Datenreihenfeld",labelField:"Beschriftungsfeld",
chartColor:"Diagrammfarbe",singleColor:"Einzelfarbe",colorByTheme:"Farbe nach Design",colorByFieldValue:"Farbe nach Feldwert",xAxisTitle:"Titel der X-Achse",xAxisHintText:"Hinweis: Titel der X-Achse",yAxisTitle:"Titel der Y-Achse",yAxisHintText:"Hinweis: Titel der Y-Achse",fieldColorLabel:"Beschriftung",fieldColorColor:"Farbe",defaultFieldSelectLabel:"Ausw\u00e4hlen",errMsgFieldValuesNotFound:"F\u00fcr das ausgew\u00e4hlte Feld konnten keine Werte gefunden werden.",errMsgSectionTitle:"Geben Sie den Abschnittstitel ein.",
errMsgFieldByValue:"W\u00e4hlen Sie den Feldwert aus.",settingTabTitle:"Einstellung",layoutTabTitle:"Layout",polarChartSelectFieldsHintText:"Hinweis: W\u00e4hlen Sie zum Erstellen des Polardiagramms Felder aus.",visibilityText:"Sichtbarkeit",fieldNameText:"Feldname",aliasNameText:"Alias",errMsgPolarFieldsRequired:"W\u00e4hlen Sie mindestens drei Felder zum Erstellen des Polardiagramms aus.",polarChartPolygonFillLabel:"F\u00fcllpolygon",polarChartPolygonFillHintText:"Hinweis: Aktivieren Sie das Kontrollk\u00e4stchen, um die Polygonf\u00fcllung im Polardiagramm anzuzeigen.",
ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"Desert",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Ireland",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",
themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Wetland",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Allgemeine Einstellungen",locationSymbolLabel:"Symbol f\u00fcr grafische Position",locationSymbolHintText:"Hinweis: Wird zum Anzeigen eines Symbols f\u00fcr die Adresse und aktivierte Position verwendet",
refreshIntervalLabel:"Aktualisierungsintervall",refreshIntervalHintText:"Hinweis: Wird zum Aktualisieren von Diagrammen basierend auf diesem Intervall verwendet. Geben Sie einen Wert zwischen 1 und 1440 Minuten ein.",errMsgRefreshInterval:"Legen Sie das Aktualisierungsintervall auf einen Wert zwischen 0 und 1440 Minuten fest.",symbolPickerPreviewText:"Vorschau:"},_localized:{}}});