// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Boldirano",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvla\u010di",insertHorizontalRule:"Horizontalno pravilo",insertOrderedList:"Numerisana lista",insertUnorderedList:"Lista oznaka",italic:"Kurziv",justifyCenter:"Poravnaj po sredini",justifyFull:"Poravnaj",justifyLeft:"Poravnaj na lijevo",justifyRight:"Poravnaj na desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovo napravi",removeFormat:"Ukloni format",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podvuci",undo:"Poni\u0161ti",unlink:"Ukloni link",createLink:"Kreiraj link",toggleDir:"Promijeni smjer",insertImage:"Umetni sliku",insertTable:"Umetni/uredi tabelu",toggleTableBorder:"Promijeni rub tabele",deleteTable:"Bri\u0161i tabelu",tableProp:"Osobina tabele",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil paragrafa",formatBlock:"Stil paragrafa",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Uvla\u010denje kartice",fullScreen:"Promijeni pun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispi\u0161i",newPage:"Nova stranica",systemShortcut:'Akcija "${0}"je dostupna u va\u0161em pretra\u017eiva\u010du kad koristite pre\u010dicu tastature. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"bez-serifa",monospace:"monoprostor",cursive:"kurziv",
fantasy:"Fantazija",noFormat:"ni\u0161ta",p:"Paragraf",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Predformatizovano",1:"xx-malo",2:"x-malo",3:"maleno",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Na\u0111i:",findTooltip:"Unesite tekst koji treba na\u0107i",replaceLabel:"Zamijeni sa:",replaceTooltip:"Unesite tekst s kojim zamijeniti",findReplace:"Na\u0111i i zamijeni",
matchCase:"Spari slovo",matchCaseTooltip:"Spari slovo",backwards:"Unazad",backwardsTooltip:"Pretra\u017euj unazad za tekst",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Na\u0111i",findButtonTooltip:"Na\u0111i tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjena ${0} pojavljivanja",eofDialogText:"zadnje pojavljivanje ${0}",eofDialogTextFind:"prona\u0111eno",eofDialogTextReplace:"zamijenjeno",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepi sadr\u017eaj iz Worda ispod okvira s tekstom. Kad ste jednom zadovoljni sa sadr\u017eajem koji ume\u0107ete, pritisnite dugme za lijepljenje. Za prekid umetanja teksta, pritisnite dugme odustani.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Osobine sidra",anchor:"Ime:",text:"Opis:",set:"Postav",cancel:"Odustani",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Citat bloka",
_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Postavke grafikona",addNewLabel:"Dodaj novi",generalSettingLabel:"Op\u0107e postavke",layerChooser:{title:"Odaberi sloj za grafikon",selectPolygonLayerLabel:"Odaberi sloj",selectPolygonLayerHintText:"Podsjetnik: ako konfigurirate vi\u0161e grafikona, tada slojevi moraju imati istu vrstu geometrije",selectRelatedTableLayerLabel:"Odaberi tablicu povezanu sa slojem",selectRelatedTableLayerHintText:"Podsjetnik: prikazane su samo tablice s broj\u010danim poljima",
errorInSelectingPolygonLayer:"Odredite sloj koji ima povezani to\u010dkasti sloj.",errorInSelectingRelatedLayer:"Odaberite va\u017ee\u0107u povezanu tablicu/sloj za sloj.",polygonLayerNotHavingRelationships:"Odabrani sloj nema povezanu tablicu/sloj."},ChartSetting:{sectionTitle:"Naslov odjeljka",sectionTitleHintText:"Podsjetnik: prikazano u naslovu zaglavlja odjeljka",chartTitle:"Naslov grafikona",chartTitleHintText:"Podsjetnik: prikazano centrirano na vrhu grafikona",chartDescription:"Opis",chartDescriptionHintText:"Podsjetnik: prikazano ispod grafikona",
chartType:"Vrsta grafikona",barChart:"Trakasti grafikon",pieChart:"Tortni grafikon",polarChart:"Polarni grafikon",dataSeriesField:"Polje serije podataka",labelField:"Polje oznake",chartColor:"Boja grafikona",singleColor:"Jedna boja",colorByTheme:"Boja prema temi",colorByFieldValue:"Boja prema vrijednosti polja",xAxisTitle:"Naslov X-osi",xAxisHintText:"Podsjetnik: naslov X-osi",yAxisTitle:"Naslov Y-osi",yAxisHintText:"Podsjetnik: naslov Y-osi",fieldColorLabel:"Oznaka",fieldColorColor:"Boja",defaultFieldSelectLabel:"Odaberi",
errMsgFieldValuesNotFound:"Nije mogu\u0107e prona\u0107i vrijednosti za odabrano polje",errMsgSectionTitle:"Unesite naslov odjeljka",errMsgFieldByValue:"Odaberite vrijednost polja",settingTabTitle:"Postavka",layoutTabTitle:"Izgled",polarChartSelectFieldsHintText:"Podsjetnik: odaberite polja za generiranje polarnog grafikona",visibilityText:"Vidljivost",fieldNameText:"Naziv polja",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Odaberite tri ili vi\u0161e polja za generiranje polarnog grafikona",
polarChartPolygonFillLabel:"Ispuni poligon",polarChartPolygonFillHintText:"Podsjetnik: odaberite potvrdni okvir za prikaz polarnog grafikona ispunjenog poligona",ThemeSelector:{themeAdobebricks:"\u0106erpi\u010d",themeAlgae:"Alge",themeBahamation:"Bahamation",themeBlueDusk:"Plavi sumrak",themeCubanShirts:"Kubanske ko\u0161ulje",themeDesert:"Pustinja",themeDistinctive:"Izrazito",themeDollar:"Dolar",themeGrasshopper:"Skakavac",themeGrasslands:"Pa\u0161njaci",themeGreySkies:"Sivo nebo",themeHarmony:"Sklad",
themeIndigoNation:"IndigoNation",themeIreland:"Irska",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Vla\u017eno podru\u010dje",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Op\u0107e postavke",
locationSymbolLabel:"Grafi\u010dki simbol lokacije",locationSymbolHintText:"Posjetnik: upotrebljava se za prikaz simbola za adresu i lokaciju na koju ste kliknuli",refreshIntervalLabel:"Interval osvje\u017eavanja",refreshIntervalHintText:"Posjetnik: upotrebljava se za osvje\u017eavanje grafikona na temelju ovog intervala. Odredite vrijednost izme\u0111u 1 do 1440 minuta",errMsgRefreshInterval:"Odredite interval osvje\u017eavanja izme\u0111u 0 do 1440 minuta",symbolPickerPreviewText:"Pretpregled:"},
_localized:{}}});