// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fed",copy:"Kopi\u00e9r",cut:"Klip","delete":"Slet",indent:"Indrykning",insertHorizontalRule:"Vandret linje",insertOrderedList:"Nummereret liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Centreret",justifyFull:"Lige margener",justifyLeft:"Venstrejusteret",justifyRight:"H\u00f8jrejusteret",outdent:"Udrykning",paste:"S\u00e6t ind",redo:"Annull\u00e9r Fortryd",removeFormat:"Fjern format",selectAll:"Mark\u00e9r alle",strikethrough:"Gennemstreget",
subscript:"S\u00e6nket skrift",superscript:"H\u00e6vet skrift",underline:"Understreget",undo:"Fortryd",unlink:"Fjern link",createLink:"Opret link",toggleDir:"Skift retning",insertImage:"Inds\u00e6t billede",insertTable:"Inds\u00e6t/redig\u00e9r tabel",toggleTableBorder:"Skift tabelramme",deleteTable:"Slet tabel",tableProp:"Tabelegenskab",htmlToggle:"HTML-kilde",foreColor:"Forgrundsfarve",hiliteColor:"Baggrundsfarve",plainFormatBlock:"Afsnitstypografi",formatBlock:"Afsnitstypografi",fontSize:"Skriftst\u00f8rrelse",
fontName:"Skriftnavn",tabIndent:"Tabulatorindrykning",fullScreen:"Fuld sk\u00e6rm til/fra",viewSource:"Vis HTML-kilde",print:"Udskriv",newPage:"Ny side",systemShortcut:'Funktionen "${0}" kan kun bruges i din browser med en tastaturgenvej. Brug ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrifttype",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasy",
noFormat:"Ingen",p:"Afsnit",h1:"Overskrift",h2:"Underoverskrift",h3:"Underunderoverskrift",pre:"Forudformateret",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Eksempel",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8g:",findTooltip:"Indtast tekst, du vil s\u00f8ge efter",replaceLabel:"Erstat med:",replaceTooltip:"Indtast tekst, du vil erstatte med",findReplace:"S\u00f8g og erstat",
matchCase:"Forskel p\u00e5 store og sm\u00e5 bogstaver",matchCaseTooltip:"Forskel p\u00e5 store og sm\u00e5 bogstaver",backwards:"Bagl\u00e6ns",backwardsTooltip:"S\u00f8g bagl\u00e6ns i teksten",replaceAllButton:"Erstat alle",replaceAllButtonTooltip:"Erstat i hele teksten",findButton:"S\u00f8g",findButtonTooltip:"Find teksten",replaceButton:"Erstat",replaceButtonTooltip:"Erstat teksten",replaceDialogText:"${0} forekomster erstattet.",eofDialogText:"Sidste forekomst ${0}",eofDialogTextFind:"fundet",
eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Inds\u00e6t fra Word",instructions:"Inds\u00e6t indholdet fra Word i tekstfeltet nedenfor. Klik p\u00e5 knappen Inds\u00e6t, n\u00e5r du er tilfreds med indholdet. Tryk p\u00e5 knappen Annull\u00e9r for at fortryde inds\u00e6ttelsen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inds\u00e6t anker",title:"Egenskaber for anker",anchor:"Navn:",text:"Beskrivelse:",set:"Defin\u00e9r",
cancel:"Annull\u00e9r",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokanf\u00f8rselstegn",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Diagramindstillinger",addNewLabel:"Tilf\u00f8j nyt",generalSettingLabel:"Generelle indstillinger",layerChooser:{title:"V\u00e6lg lag, der skal oprettes diagram over",selectPolygonLayerLabel:"V\u00e6lg lag",selectPolygonLayerHintText:"Tip: Hvis du konfigurerer flere diagrammer, skal lagene v\u00e6re af samme geometritype",
selectRelatedTableLayerLabel:"V\u00e6lg den tabel, der er knyttet til laget",selectRelatedTableLayerHintText:"Tip: Kun tabeller med numeriske felter vises",errorInSelectingPolygonLayer:"V\u00e6lg et lag med et tilknyttet punktlag.",errorInSelectingRelatedLayer:"V\u00e6lg en gyldig tilknyttet tabel/lag til laget.",polygonLayerNotHavingRelationships:"Det valgte lag har ikke nogen tilknyttede tabeller/lag."},ChartSetting:{sectionTitle:"Sektionstitel",sectionTitleHintText:"Tip: Vises i sektionsheader-titlen",
chartTitle:"Diagramtitel",chartTitleHintText:"Tip: Vises centreret \u00f8verst i diagrammet",chartDescription:"Beskrivelse",chartDescriptionHintText:"Tip: Vises under diagrammet",chartType:"Diagramtype",barChart:"S\u00f8jlediagram",pieChart:"Cirkeldiagram",polarChart:"Polardiagram",dataSeriesField:"Dataseriefelt",labelField:"Etiketfelt",chartColor:"Diagramfarve",singleColor:"Enkelt farve",colorByTheme:"Farve efter tema",colorByFieldValue:"Farve efter feltv\u00e6rdi",xAxisTitle:"X-aksetitel",xAxisHintText:"Tip: X-aksetitel",
yAxisTitle:"Y-aksetitel",yAxisHintText:"Tip: Y-aksetitel",fieldColorLabel:"M\u00e6rke",fieldColorColor:"Farve",defaultFieldSelectLabel:"V\u00e6lg",errMsgFieldValuesNotFound:"Kan ikke finde v\u00e6rdier for det valgte felt",errMsgSectionTitle:"Angiv sektionstitlen",errMsgFieldByValue:"V\u00e6lg feltv\u00e6rdi",settingTabTitle:"Indstilling",layoutTabTitle:"Layout",polarChartSelectFieldsHintText:"Tip: V\u00e6lg felter for at generere et polardiagram",visibilityText:"Synlighed",fieldNameText:"Feltnavn",
aliasNameText:"Alias",errMsgPolarFieldsRequired:"V\u00e6lg tre eller flere felter for at generere et polardiagram",polarChartPolygonFillLabel:"Udfyld polygon",polarChartPolygonFillHintText:"Tip: Mark\u00e9r afkrydsningsfeltet for at vise polygonfyld i polardiagrammet",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Alger",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"\u00d8rken",themeDistinctive:"Karakteristisk",themeDollar:"Dollar",themeGrasshopper:"Gr\u00e6shoppe",
themeGrasslands:"Gr\u00e6smarker",themeGreySkies:"Gr\u00e5Skyer",themeHarmony:"Harmoni",themeIndigoNation:"IndigoNation",themeIreland:"Irland",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"V\u00e5domr\u00e5de",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",
themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Generelle indstillinger",locationSymbolLabel:"Grafisk positionssymbol",locationSymbolHintText:"Tip: Bruges til at vise symbol for adressen og position, der er klikket p\u00e5",refreshIntervalLabel:"Opdateringsinterval",refreshIntervalHintText:"Tip: Bruges til at opdatere diagrammer baseret p\u00e5 dette interval. Angiv en v\u00e6rdi mellem 1 og 1440 minutter",errMsgRefreshInterval:"Angiv opdateringsinterval mellem 0 og 1440 minutter",
symbolPickerPreviewText:"Forh\u00e5ndsvisning:"},_localized:{}}});