// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljaj",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvuci",insertHorizontalRule:"Vodoravno ravnalo",insertOrderedList:"Numerirani popis",insertUnorderedList:"Popis s grafi\u010dkim oznakama",italic:"Kurziv",justifyCenter:"Centriraj",justifyFull:"Poravnaj",justifyLeft:"Poravnaj lijevo",justifyRight:"Poravnaj desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovno napravi",removeFormat:"Ukloni oblikovanje",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podcrtaj",undo:"Poni\u0161ti",unlink:"Ukloni vezu",createLink:"Kreiraj vezu",toggleDir:"Prebaci smjer",insertImage:"Umetni sliku",insertTable:"Umetni/Uredi tablicu",toggleTableBorder:"Prebaci rub tablice",deleteTable:"Izbri\u0161i tablicu",tableProp:"Svojstvo tablice",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil odlomka",formatBlock:"Stil odlomka",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Tabulator uvla\u010denja",fullScreen:"Prebaci na potpun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispis",newPage:"Nova stranica",systemShortcut:'"${0}" akcija je dostupna jedino u va\u0161em pregledniku upotrebom pre\u010dice tipkovnice. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Oblikovanje",serif:"serif","sans-serif":"sans-serif",monospace:"jednaki razmak",cursive:"rukopisni",
fantasy:"fantastika",noFormat:"Nijedan",p:"Odlomak",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Prethodno formatirano",1:"vrlo vrlo malo",2:"vrlo malo",3:"malo",4:"srednje",5:"veliko",6:"vrlo veliko",7:"vrlo vrlo veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Tra\u017ei:",findTooltip:"Unesi tekst pretrage",replaceLabel:"Zamijeni s:",replaceTooltip:"Unesi tekst za zamjenu",findReplace:"Tra\u017ei i zamijeni",
matchCase:"Usporedi velika/mala slova",matchCaseTooltip:"Usporedi velika/mala slova",backwards:"Natrag",backwardsTooltip:"Pretra\u017ei tekst u prethodnim koracima",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Tra\u017ei",findButtonTooltip:"Tra\u017ei tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjeno ${0} pojavljivanja.",eofDialogText:"Zadnje pojavljivanje ${0}",eofDialogTextFind:"na\u0111eno",eofDialogTextReplace:"zamijenjeno",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepite sadr\u017eaj iz Worda u donji tekstni okvir. Kad ste zadovoljni sa sadr\u017eajem za umetanje, pritisnite tipku Zalijepi.  Za prekid umetanja teksta, pritisnite tipku Opoziv.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Svojstva sidra",anchor:"Naziv:",text:"Opis:",set:"Postavi",cancel:"Opoziv",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Dugi citat",
_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Postavke grafikona",addNewLabel:"Dodaj novi",generalSettingLabel:"Op\u0107e postavke",layerChooser:{title:"Odaberi sloj za grafikon",selectPolygonLayerLabel:"Odaberi sloj",selectPolygonLayerHintText:"Podsjetnik: ako konfigurirate vi\u0161e grafikona, tada slojevi moraju imati istu vrstu geometrije",selectRelatedTableLayerLabel:"Odaberi tablicu povezanu sa slojem",selectRelatedTableLayerHintText:"Podsjetnik: prikazane su samo tablice s broj\u010danim poljima",
errorInSelectingPolygonLayer:"Odredite sloj koji ima povezani to\u010dkasti sloj.",errorInSelectingRelatedLayer:"Odaberite va\u017ee\u0107u povezanu tablicu/sloj za sloj.",polygonLayerNotHavingRelationships:"Odabrani sloj nema povezanu tablicu/sloj."},ChartSetting:{sectionTitle:"Naslov odjeljka",sectionTitleHintText:"Podsjetnik: prikazano u naslovu zaglavlja odjeljka",chartTitle:"Naslov grafikona",chartTitleHintText:"Podsjetnik: prikazano centrirano na vrhu grafikona",chartDescription:"Opis",chartDescriptionHintText:"Podsjetnik: prikazano ispod grafikona",
chartType:"Vrsta grafikona",barChart:"Trakasti grafikon",pieChart:"Tortni grafikon",polarChart:"Polarni grafikon",dataSeriesField:"Polje serije podataka",labelField:"Polje oznake",chartColor:"Boja grafikona",singleColor:"Jedna boja",colorByTheme:"Boja prema temi",colorByFieldValue:"Boja prema vrijednosti polja",xAxisTitle:"Naslov X-osi",xAxisHintText:"Podsjetnik: naslov X-osi",yAxisTitle:"Naslov Y-osi",yAxisHintText:"Podsjetnik: naslov Y-osi",fieldColorLabel:"Oznaka",fieldColorColor:"Boja",defaultFieldSelectLabel:"Odaberi",
errMsgFieldValuesNotFound:"Nije mogu\u0107e prona\u0107i vrijednosti za odabrano polje",errMsgSectionTitle:"Unesite naslov odjeljka",errMsgFieldByValue:"Odaberite vrijednost polja",settingTabTitle:"Postavka",layoutTabTitle:"Izgled",polarChartSelectFieldsHintText:"Podsjetnik: odaberite polja za generiranje polarnog grafikona",visibilityText:"Vidljivost",fieldNameText:"Naziv polja",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Odaberite tri ili vi\u0161e polja za generiranje polarnog grafikona",
polarChartPolygonFillLabel:"Ispuni poligon",polarChartPolygonFillHintText:"Podsjetnik: odaberite potvrdni okvir za prikaz polarnog grafikona ispunjenog poligona",ThemeSelector:{themeAdobebricks:"\u0106erpi\u010d",themeAlgae:"Alge",themeBahamation:"Bahamation",themeBlueDusk:"Plavi sumrak",themeCubanShirts:"Kubanske ko\u0161ulje",themeDesert:"Pustinja",themeDistinctive:"Izrazito",themeDollar:"Dolar",themeGrasshopper:"Skakavac",themeGrasslands:"Pa\u0161njaci",themeGreySkies:"Sivo nebo",themeHarmony:"Sklad",
themeIndigoNation:"IndigoNation",themeIreland:"Irska",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Vla\u017eno podru\u010dje",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Op\u0107e postavke",
locationSymbolLabel:"Grafi\u010dki simbol lokacije",locationSymbolHintText:"Posjetnik: upotrebljava se za prikaz simbola za adresu i lokaciju na koju ste kliknuli",refreshIntervalLabel:"Interval osvje\u017eavanja",refreshIntervalHintText:"Posjetnik: upotrebljava se za osvje\u017eavanje grafikona na temelju ovog intervala. Odredite vrijednost izme\u0111u 1 do 1440 minuta",errMsgRefreshInterval:"Odredite interval osvje\u017eavanja izme\u0111u 0 do 1440 minuta",symbolPickerPreviewText:"Pretpregled:"},
_localized:{}}});