// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pary\u0161kintasis",copy:"Kopijuoti",cut:"Kirpti","delete":"Pa\u0161alinti",indent:"\u012etrauka",insertHorizontalRule:"Horizontali linija",insertOrderedList:"Sunumeruotas s\u0105ra\u0161as",insertUnorderedList:"S\u0105ra\u0161as su \u017eenkleliais",italic:"Pasvirasis",justifyCenter:"Lygiuoti centre",justifyFull:"Abipus\u0117 lygiuot\u0117",justifyLeft:"Lygiuoti kair\u0117je",justifyRight:"Lygiuoti de\u0161in\u0117je",outdent:"Atvirk\u0161tin\u0117 \u012ftrauka",
paste:"\u012eklijuoti",redo:"Gr\u0105\u017einti",removeFormat:"Pa\u0161alinti formatavim\u0105",selectAll:"\u017dym\u0117ti visk\u0105",strikethrough:"Perbrauktasis",subscript:"Apatinis indeksas",superscript:"Vir\u0161utinis indeksas",underline:"Pabrauktasis",undo:"At\u0161aukti",unlink:"Pa\u0161alinti nuorod\u0105",createLink:"Kurti nuorod\u0105",toggleDir:"Perjungti krypt\u012f",insertImage:"\u012eterpti vaizd\u0105",insertTable:"\u012eterpti / redaguoti vaizd\u0105",toggleTableBorder:"Perjungti lentel\u0117s kra\u0161tin\u0119",
deleteTable:"Pa\u0161alinti lentel\u0119",tableProp:"Lentel\u0117s savyb\u0117",htmlToggle:"HTML \u0161altinis",foreColor:"Priekinio plano spalva",hiliteColor:"Fono spalva",plainFormatBlock:"Pastraipos stilius",formatBlock:"Pastraipos stilius",fontSize:"\u0160rifto dydis",fontName:"\u0160rifto pavadinimas",tabIndent:"Tabuliacijos \u012ftrauka",fullScreen:"Perjungti vis\u0105 ekran\u0105",viewSource:"Per\u017ei\u016br\u0117ti HTML \u0161altin\u012f",print:"Spausdinti",newPage:"Naujas puslapis",systemShortcut:'"${0}" veiksm\u0105 galima atlikti nar\u0161ykl\u0117je tik naudojant spart\u0173j\u012f klavi\u0161\u0105. Naudokite ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dydis",fontName:"\u0160riftas",formatBlock:"Formatuoti",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"N\u0117ra",p:"Pastraipa",h1:"Antra\u0161t\u0117",h2:"Paantra\u0161t\u0117",h3:"Antrin\u0117 paantra\u0161t\u0117",pre:"I\u0161 anksto suformatuota",1:"xx ma\u017eas",2:"x ma\u017eas",3:"ma\u017eas",4:"vidutinis",5:"didelis",6:"x didelis",
7:"xx didelis",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",
findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Diagramos nustatymai",addNewLabel:"Prid\u0117ti nauj\u0105",generalSettingLabel:"Bendrieji parametrai",layerChooser:{title:"Pasirinkite diagramos\u00a0sluoksn\u012f",selectPolygonLayerLabel:"Pasirinkite sluoksn\u012f",
selectPolygonLayerHintText:"Patarimas: jei konfig\u016bruojate kelias diagramas, sluoksniai turi b\u016bti to paties geometrijos tipo",selectRelatedTableLayerLabel:"Pasirinkti su sluoksniu susijusi\u0105 lentel\u0119",selectRelatedTableLayerHintText:"Patarimas: rodomos tik lentel\u0117s su skaitiniais laukais",errorInSelectingPolygonLayer:"Pasirinkite sluoksn\u012f, kuriame yra susijusi\u0173 ta\u0161k\u0173 sluoksnis.",errorInSelectingRelatedLayer:"Pasirinkite tinkam\u0105 lentel\u0119 / sluoksn\u012f, susijus\u012f su sluoksniu.",
polygonLayerNotHavingRelationships:"Pasirinktas sluoksnis neturi susijusi\u0173 lenteli\u0173 / sluoksni\u0173."},ChartSetting:{sectionTitle:"Skilties pavadinimas",sectionTitleHintText:"Patarimas: rodoma skilties antra\u0161t\u0117s pavadinime",chartTitle:"Diagramos pavadinimas",chartTitleHintText:"U\u017euomina: rodomas centre diagramos vir\u0161uje",chartDescription:"Apra\u0161ymas",chartDescriptionHintText:"U\u017euomina: rodomas po diagrama",chartType:"Diagramos tipas",barChart:"Stulpelin\u0117 diagrama",
pieChart:"Skritulin\u0117 diagrama",polarChart:"Polin\u0117 diagrama",dataSeriesField:"Duomen\u0173 serijos laukas",labelField:"\u017dym\u0117s laukas",chartColor:"Diagramos spalva",singleColor:"Viena spalva",colorByTheme:"Spalva pagal tem\u0105",colorByFieldValue:"Spalvos pagal lauk\u0173 reik\u0161m\u0119",xAxisTitle:"X a\u0161ies pavadinimas",xAxisHintText:"Patarimas: X a\u0161ies pavadinimas",yAxisTitle:"Y a\u0161ies pavadinimas",yAxisHintText:"Patarimas: Y a\u0161ies pavadinimas",fieldColorLabel:"\u017dym\u0117",
fieldColorColor:"Spalva",defaultFieldSelectLabel:"Pasirinkite",errMsgFieldValuesNotFound:"Nepavyko rasti pasirinkto lauko reik\u0161mi\u0173",errMsgSectionTitle:"\u012eveskite skilties pavadinim\u0105",errMsgFieldByValue:"Pasirinkite lauko reik\u0161m\u0119",settingTabTitle:"Nustatymas",layoutTabTitle:"Maketas",polarChartSelectFieldsHintText:"U\u017euomina: pasirinkite laukus, kuriais remdamiesi norite sugeneruoti polin\u0119 diagram\u0105",visibilityText:"Matomumas",fieldNameText:"Lauko pavadinimas",
aliasNameText:"Pseudonimas",errMsgPolarFieldsRequired:"Pasirinkite tris ar daugiau lauk\u0173, kuriais remdamiesi norite sugeneruoti polin\u0119 diagram\u0105",polarChartPolygonFillLabel:"U\u017epildykite plot\u0105",polarChartPolygonFillHintText:"U\u017euomina: pasirinkite \u017eym\u0117s langel\u012f, parodant\u012f ploto u\u017epildym\u0105 polin\u0117je diagramoje",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",
themeDesert:"Desert",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Ireland",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Wetland",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",
themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Bendrieji parametrai",locationSymbolLabel:"Grafinis vietos simbolis",locationSymbolHintText:"Patarimas: naudojama adreso ir paspaudimo vietos simboliui rodyti",refreshIntervalLabel:"Atnaujinimo intervalas",refreshIntervalHintText:"Patarimas: naudojama diagramoms atnaujinti, atsi\u017evelgiant \u012f \u0161\u012f interval\u0105. Nurodykite reik\u0161m\u0119 nuo 1 iki 1440 minu\u010di\u0173",
errMsgRefreshInterval:"Nurodykite atnaujinimo interval\u0105 nuo 0 iki 1440 minu\u010di\u0173",symbolPickerPreviewText:"Per\u017ei\u016bra:"},_localized:{}}});