// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Gras",copy:"Copier",cut:"Couper","delete":"Supprimer",indent:"Retrait",insertHorizontalRule:"R\u00e8gle horizontale",insertOrderedList:"Liste num\u00e9rot\u00e9e",insertUnorderedList:"Liste \u00e0 puces",italic:"Italique",justifyCenter:"Aligner au centre",justifyFull:"Justifier",justifyLeft:"Aligner \u00e0 gauche",justifyRight:"Aligner \u00e0 droite",outdent:"Retrait n\u00e9gatif",paste:"Coller",redo:"R\u00e9tablir",removeFormat:"Supprimer la mise en forme",
selectAll:"S\u00e9lectionner tout",strikethrough:"Barrer",subscript:"Indice",superscript:"Exposant",underline:"Souligner",undo:"Annuler",unlink:"Supprimer le lien",createLink:"Cr\u00e9er un lien",toggleDir:"Changer de sens",insertImage:"Ins\u00e9rer une image",insertTable:"Ins\u00e9rer/Modifier un tableau",toggleTableBorder:"Afficher/Masquer la bordure du tableau",deleteTable:"Supprimer le tableau",tableProp:"Propri\u00e9t\u00e9 du tableau",htmlToggle:"Source HTML",foreColor:"Couleur avant-plan",
hiliteColor:"Couleur arri\u00e8re-plan",plainFormatBlock:"Style de paragraphe",formatBlock:"Style de paragraphe",fontSize:"Taille de police",fontName:"Nom de police",tabIndent:"Retrait de tabulation",fullScreen:"Basculer en plein \u00e9cran",viewSource:"Afficher la source HTML",print:"Imprimer",newPage:"Nouvelle page",systemShortcut:'Action "${0}" uniquement disponible dans votre navigateur via un raccourci clavier. Utilisez ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Taille",
fontName:"Police",formatBlock:"Mise en forme",serif:"serif","sans-serif":"sans serif",monospace:"espacement fixe",cursive:"cursive",fantasy:"fantaisie",noFormat:"N\u00e9ant",p:"Paragraphe",h1:"En-t\u00eate",h2:"Sous-en-t\u00eate",h3:"Sous-sous-en-t\u00eate",pre:"Pr\u00e9-mise en forme",1:"tr\u00e8s tr\u00e8s petite",2:"tr\u00e8s petite",3:"petite",4:"moyenne",5:"grande",6:"tr\u00e8s grande",7:"tr\u00e8s tr\u00e8s grande",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Aper\u00e7u",_localized:{}},
"dojox/editor/plugins/nls/FindReplace":{findLabel:"Rechercher :",findTooltip:"Entrez le texte \u00e0 rechercher",replaceLabel:"Remplacer par :",replaceTooltip:"Entrez le texte de remplacement",findReplace:"Rechercher et remplacer",matchCase:"Respecter la casse",matchCaseTooltip:"Respecter la casse",backwards:"Vers l'arri\u00e8re",backwardsTooltip:"Recherchez le texte vers l'arri\u00e8re",replaceAllButton:"Remplacer tout",replaceAllButtonTooltip:"Remplacez tout le texte",findButton:"Rechercher",findButtonTooltip:"Recherchez le texte",
replaceButton:"Remplacer",replaceButtonTooltip:"Remplacez le texte",replaceDialogText:"${0} occurrence(s) remplac\u00e9e(s)",eofDialogText:"Derni\u00e8re occurrence ${0}",eofDialogTextFind:"trouv\u00e9",eofDialogTextReplace:"remplac\u00e9",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Coller depuis Word",instructions:"Collez le contenu Word dans la zone de texte ci-dessous. Quand le contenu \u00e0 ins\u00e9rer vous convient, appuyez sur le bouton Coller. Pour annuler l'insertion du texte, utilisez le bouton Annuler.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Ins\u00e9rer un point d'ancrage",title:"Propri\u00e9t\u00e9s du point d'ancrage",anchor:"Nom :",text:"Description :",set:"D\u00e9finir",cancel:"Annuler",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Bloc de citation",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Param\u00e8tres de diagramme",addNewLabel:"Ajouter une action",generalSettingLabel:"param\u00e8tres g\u00e9n\u00e9raux",
layerChooser:{title:"S\u00e9lectionner une couche \u00e0 afficher sous forme de diagramme",selectPolygonLayerLabel:"S\u00e9lectionner une couche",selectPolygonLayerHintText:"Astuce\u00a0: si vous configurez plusieurs diagrammes, les couches doivent \u00eatre du m\u00eame type de g\u00e9om\u00e9trie",selectRelatedTableLayerLabel:"S\u00e9lectionner une table associ\u00e9e \u00e0 une couche",selectRelatedTableLayerHintText:"Astuce\u00a0: seules les tables contenant des champs num\u00e9riques sont affich\u00e9es",
errorInSelectingPolygonLayer:"S\u00e9lectionnez une couche poss\u00e9dant une couche de points associ\u00e9e.",errorInSelectingRelatedLayer:"S\u00e9lectionnez une table/couche associ\u00e9e valide pour la couche.",polygonLayerNotHavingRelationships:"La couche s\u00e9lectionn\u00e9e ne poss\u00e8de pas de table/couche associ\u00e9e."},ChartSetting:{sectionTitle:"Titre de la section",sectionTitleHintText:"Astuce\u00a0: affich\u00e9 dans le titre de l\u2019en-t\u00eate de la section",chartTitle:"Titre du diagramme",
chartTitleHintText:"Astuce\u00a0: affich\u00e9 de fa\u00e7on centr\u00e9e en haut du diagramme",chartDescription:"Description",chartDescriptionHintText:"Astuce\u00a0: affich\u00e9 sous le diagramme",chartType:"Type de diagramme",barChart:"Diagramme \u00e0 barres",pieChart:"Diagramme circulaire",polarChart:"Diagramme polaire",dataSeriesField:"Champ de s\u00e9rie de donn\u00e9es",labelField:"Champ d\u2019\u00e9tiquette",chartColor:"Couleur du diagramme",singleColor:"Uni",colorByTheme:"Couleur par th\u00e8me",
colorByFieldValue:"Couleur par valeur de champ",xAxisTitle:"Titre de l\u2019axe des\u00a0x",xAxisHintText:"Astuce\u00a0: titre de l\u2019axe des\u00a0x",yAxisTitle:"Titre de l\u2019axe des\u00a0y",yAxisHintText:"Astuce\u00a0: titre de l\u2019axe des\u00a0y",fieldColorLabel:"Etiqueter",fieldColorColor:"Couleur",defaultFieldSelectLabel:"S\u00e9lectionner",errMsgFieldValuesNotFound:"Impossible de trouver des valeurs pour le champ s\u00e9lectionn\u00e9",errMsgSectionTitle:"Saisissez le titre de la section",
errMsgFieldByValue:"S\u00e9lectionnez une valeur de champ",settingTabTitle:"Param\u00e8tre",layoutTabTitle:"Mise en page",polarChartSelectFieldsHintText:"Astuce\u00a0: s\u00e9lectionnez les champs pour g\u00e9n\u00e9rer le diagramme polaire",visibilityText:"Visibilit\u00e9",fieldNameText:"Nom de champ",aliasNameText:"Alias",errMsgPolarFieldsRequired:"S\u00e9lectionnez trois champs ou plus pour g\u00e9n\u00e9rer le diagramme polaire",polarChartPolygonFillLabel:"Remplir le polygone",polarChartPolygonFillHintText:"Astuce\u00a0: cochez la case pour afficher le remplissage de polygones dans le diagramme polaire",
ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"D\u00e9sert",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Irlande",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",
themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Zone humide",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Param\u00e8tres g\u00e9n\u00e9raux",locationSymbolLabel:"Symbole d\u2019emplacement graphique",locationSymbolHintText:"Astuce\u00a0: utilis\u00e9 pour afficher le symbole d\u2019adresse et d\u2019emplacement s\u00e9lectionn\u00e9",
refreshIntervalLabel:"Intervalle d'actualisation",refreshIntervalHintText:"Astuce\u00a0: utilis\u00e9 pour actualiser les diagrammes en fonction de cet intervalle. Sp\u00e9cifiez une valeur entre 1 et 1\u00a0440\u00a0minutes",errMsgRefreshInterval:"Sp\u00e9cifiez l\u2019intervalle d\u2019actualisation entre 0 et 1\u00a0440\u00a0minutes",symbolPickerPreviewText:"Aper\u00e7u :"},_localized:{}}});