// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Cortar","delete":"Eliminar",indent:"Indentar",insertHorizontalRule:"R\u00e9gua horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista marcada",italic:"It\u00e1lico",justifyCenter:"Alinhar ao centro",justifyFull:"Justificar",justifyLeft:"Alinhar \u00e0 esquerda",justifyRight:"Alinhar \u00e0 direita",outdent:"Recuar",paste:"Colar",redo:"Repetir",removeFormat:"Remover formato",selectAll:"Seleccionar tudo",strikethrough:"Rasurado",
subscript:"Inferior \u00e0 linha",superscript:"Superior \u00e0 linha",underline:"Sublinhado",undo:"Anular",unlink:"Remover liga\u00e7\u00e3o",createLink:"Criar liga\u00e7\u00e3o",toggleDir:"Alternar direc\u00e7\u00e3o",insertImage:"Inserir imagem",insertTable:"Inserir/Editar tabela",toggleTableBorder:"Alternar contorno da tabela",deleteTable:"Eliminar tabela",tableProp:"Propriedades da tabela",htmlToggle:"Origem HTML",foreColor:"Cor de primeiro plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de par\u00e1grafo",
formatBlock:"Estilo de par\u00e1grafo",fontSize:"Tamanho do tipo de letra",fontName:"Nome do tipo de letra",tabIndent:"Indentar com a tecla Tab",fullScreen:"Alternar ecr\u00e3 completo",viewSource:"Ver origem HTML",print:"Imprimir",newPage:"Nova p\u00e1gina",systemShortcut:'A ac\u00e7\u00e3o "${0}" apenas est\u00e1 dispon\u00edvel no navegador utilizando um atalho de teclado. Utilize ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Tamanho",
fontName:"Tipo de letra",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Nenhum",p:"Par\u00e1grafo",h1:"T\u00edtulo",h2:"Sub-t\u00edtulo",h3:"Sub-subt\u00edtulo",pre:"Pr\u00e9-formatado",1:"xxs",2:"xs",3:"small",4:"medium",5:"large",6:"xl",7:"xxl",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pr\u00e9-visualizar",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Localizar:",findTooltip:"Introduzir texto a localizar",
replaceLabel:"Substituir por:",replaceTooltip:"Introduzir texto de substitui\u00e7\u00e3o",findReplace:"Localizar e substituir",matchCase:"Correspond\u00eancia de mai\u00fasculas/min\u00fasculas",matchCaseTooltip:"Correspond\u00eancia de mai\u00fasculas/min\u00fasculas",backwards:"Para tr\u00e1s",backwardsTooltip:"Procura de texto para tr\u00e1s",replaceAllButton:"Substituir tudo",replaceAllButtonTooltip:"Substituir todo o texto",findButton:"Localizar",findButtonTooltip:"Localizar o texto",replaceButton:"Substituir",
replaceButtonTooltip:"Substituir o texto",replaceDialogText:"Foram substitu\u00eddas ${0} ocorr\u00eancias.",eofDialogText:"\u00daltima ocorr\u00eancia ${0}",eofDialogTextFind:"localizado",eofDialogTextReplace:"substitu\u00eddo",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Colar do Word",instructions:"Cole o conte\u00fado do Word na caixa de texto abaixo. Ap\u00f3s estar satisfeito com o conte\u00fado a inserir, prima o bot\u00e3o de colagem. Para cancelar a inser\u00e7\u00e3o de texto, prima o bot\u00e3o de cancelamento.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserir \u00e2ncora",title:"Propriedades da \u00e2ncora",anchor:"Nome:",text:"Descri\u00e7\u00e3o:",set:"Definir",cancel:"Cancelar",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Defini\u00e7\u00f5es de gr\u00e1fico",addNewLabel:"Adicionar novo",generalSettingLabel:"Configura\u00e7\u00f5es gerais",layerChooser:{title:"Seleccionar camada para gr\u00e1fico",
selectPolygonLayerLabel:"Seleccionar Camada",selectPolygonLayerHintText:"Sugest\u00e3o: Se configurando m\u00faltiplos gr\u00e1ficos, ent\u00e3o camadas devem ser do mesmo tipo geom\u00e9trico",selectRelatedTableLayerLabel:"Seleccionar tabela relacionada a camada",selectRelatedTableLayerHintText:"Sugest\u00e3o: Apenas tabelas com campos num\u00e9ricos s\u00e3o exibidos",errorInSelectingPolygonLayer:"Por favor seleccione uma camada que tem uma camada de ponto relacionado.",errorInSelectingRelatedLayer:"Por favor seleccione uma tabela/camada relacionada v\u00e1lida para camada.",
polygonLayerNotHavingRelationships:"Seleccionar camada que n\u00e3o tenha qualuqer tabela/camada relacionada"},ChartSetting:{sectionTitle:"T\u00edtulo da sec\u00e7\u00e3o",sectionTitleHintText:"Sugest\u00e3o: Exibido no t\u00edtulo do cabe\u00e7alho da sec\u00e7\u00e3o",chartTitle:"T\u00edtulo de gr\u00e1fico",chartTitleHintText:"Dica: Exibido centrado por cima do gr\u00e1fico",chartDescription:"Descri\u00e7\u00e3o",chartDescriptionHintText:"Dica: Exibido abaixo do gr\u00e1fico",chartType:"Tipo de gr\u00e1fico",
barChart:"Gr\u00e1fico de barras",pieChart:"Gr\u00e1fico circular",polarChart:"Gr\u00e1fico polar",dataSeriesField:"Campo de s\u00e9rie de dados",labelField:"Campo de r\u00f3tulo",chartColor:"Cor de gr\u00e1fico",singleColor:"Cor \u00fanica",colorByTheme:"Cor por tema",colorByFieldValue:"Cor por campo de valor",xAxisTitle:"T\u00edtulo eixo-x",xAxisHintText:"Sugest\u00e3o: T\u00edtulo eixo-x",yAxisTitle:"T\u00edtulo eixo-y",yAxisHintText:"Sugest\u00e3o: T\u00edtulo eixo-y",fieldColorLabel:"R\u00f3tulo",
fieldColorColor:"Cor",defaultFieldSelectLabel:"Seleccionar",errMsgFieldValuesNotFound:"Incapaz de descobrir valores para o campo seleccionado",errMsgSectionTitle:"Por favor introduza o t\u00edtulo de sec\u00e7\u00e3o",errMsgFieldByValue:"Por favor seleccione valor de campo",settingTabTitle:"Defini\u00e7\u00e3o",layoutTabTitle:"Layout",polarChartSelectFieldsHintText:"Dica: Selecione campos para gerar gr\u00e1fico polar",visibilityText:"Visibilidade",fieldNameText:"Nome do Campo",aliasNameText:"Nome Alternativo",
errMsgPolarFieldsRequired:"Por favor, selecione tr\u00eas ou mais campos para gerar gr\u00e1fico polar",polarChartPolygonFillLabel:"Preencher pol\u00edgono",polarChartPolygonFillHintText:"Dica: Selecione a caixa de sele\u00e7\u00e3o para exibir o preenchimento do pol\u00edgono no gr\u00e1fico polar",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"Desert",themeDistinctive:"Distinctive",
themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Ireland",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Wetland",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",
themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Configura\u00e7\u00f5es Gerais",locationSymbolLabel:"S\u00edmbolo de gr\u00e1fico de localiza\u00e7\u00e3o",locationSymbolHintText:"Sugest\u00e3o: Usado para exibir s\u00edmbolo para endere\u00e7o e clique localiza\u00e7\u00e3o",refreshIntervalLabel:"Intervalo de actualiza\u00e7\u00e3o",refreshIntervalHintText:"Sugest\u00e3o: Usado para actualizar gr\u00e1ficos baseado neste intervalo. Especifique um valor entre 1 at\u00e9 1440 minutos",
errMsgRefreshInterval:"Por favor especifique o intervalo de actualiza\u00e7\u00e3o entre 0 e 1440 minutos",symbolPickerPreviewText:"Visualizar:"},_localized:{}}});