// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Treknraksts",copy:"Kop\u0113t",cut:"Izgriezt","delete":"Dz\u0113st",indent:"Atk\u0101pe",insertHorizontalRule:"Horizont\u0101l\u0101 m\u0113rjosla",insertOrderedList:"Numur\u0113ts saraksts",insertUnorderedList:"Saraksts ar aizz\u012bm\u0113m",italic:"Sl\u012bpraksts",justifyCenter:"L\u012bdzin\u0101t uz centru",justifyFull:"Taisnot",justifyLeft:"L\u012bdzin\u0101t pa kreisi",justifyRight:"L\u012bdzin\u0101t pa labi",outdent:"P\u0101rkares atk\u0101pe",
paste:"Iel\u012bm\u0113t",redo:"Atcelt atsauk\u0161anu",removeFormat:"No\u0146emt format\u0113jumu",selectAll:"Izv\u0113l\u0113ties visu",strikethrough:"P\u0101rsv\u012btrojums",subscript:"Apak\u0161raksts",superscript:"Aug\u0161raksts",underline:"Pasv\u012btrojums",undo:"Atsaukt",unlink:"No\u0146emt saiti",createLink:"Izveidot saiti",toggleDir:"P\u0101rsl\u0113gt virzienu",insertImage:"Ievietot att\u0113lu",insertTable:"Ievietot/redi\u0123\u0113t tabulu",toggleTableBorder:"P\u0101rsl\u0113gt tabulas robe\u017eu",
deleteTable:"Dz\u0113st tabulu",tableProp:"Tabulas rekviz\u012bts",htmlToggle:"HTML avots",foreColor:"Priek\u0161pl\u0101na kr\u0101sa",hiliteColor:"Fona kr\u0101sa",plainFormatBlock:"Rindkopu stils",formatBlock:"Rindkopu stils",fontSize:"Fonta lielums",fontName:"Fonta nosaukums",tabIndent:"Tabul\u0113\u0161anas atk\u0101pe",fullScreen:"P\u0101rsl\u0113gt pilnekr\u0101nu",viewSource:"Skat\u012bt HTML avotu",print:"Druk\u0101t",newPage:"Jauna lapa",systemShortcut:"Darb\u012bba ${0} ir pieejama j\u016bsu p\u0101rl\u016bkprogramm\u0101, tikai izmantojot tastat\u016bras sa\u012bsni. Izmantojiet ${1}.",
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Lielums",fontName:"Fonts",formatBlock:"Form\u0101ts",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Nav",p:"Rindkopa",h1:"Virsraksts",h2:"Apak\u0161virsraksts",h3:"Apak\u0161apak\u0161virsraksts",pre:"Iepriek\u0161 format\u0113ts",1:"xx mazs",2:"x mazs",3:"mazs",4:"vid\u0113js",5:"liels",6:"x liels",7:"xx liels",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",
_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",
replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",
title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Diagrammas iestat\u012bjumi",addNewLabel:"Pievienot jaunu",generalSettingLabel:"Visp\u0101r\u012bgi iestat\u012bjumi",layerChooser:{title:"Izv\u0113lieties diagramm\u0101 att\u0113lojamo sl\u0101ni",selectPolygonLayerLabel:"Izv\u0113l\u0113ties sl\u0101ni",
selectPolygonLayerHintText:"Padoms.\u00a0Ja tiek konfigur\u0113tas vair\u0101kas diagrammas, tad sl\u0101\u0146iem j\u0101b\u016bt viena \u0123eometrijas tipa sl\u0101\u0146iem.",selectRelatedTableLayerLabel:"Izv\u0113lieties ar sl\u0101ni saist\u012bto tabulu",selectRelatedTableLayerHintText:"Padoms. Tiek r\u0101d\u012btas tikai tabulas ar skaitliskiem\u00a0laukiem",errorInSelectingPolygonLayer:"Izv\u0113lieties sl\u0101ni, kam ir saist\u012bts punktu sl\u0101nis.",errorInSelectingRelatedLayer:"Izv\u0113lieties der\u012bgu ar sl\u0101ni saist\u012bto tabulu/sl\u0101ni.",
polygonLayerNotHavingRelationships:"Izv\u0113l\u0113tajam sl\u0101nim nav nevienas saist\u012btas tabulas/sl\u0101\u0146a."},ChartSetting:{sectionTitle:"Sada\u013cas virsraksts",sectionTitleHintText:"Padoms.\u00a0R\u0101d\u012bts sada\u013cas galvenes virsrakst\u0101",chartTitle:"Diagrammas virsraksts",chartTitleHintText:"Padoms. R\u0101d\u012bts diagrammas aug\u0161da\u013cas centr\u0101",chartDescription:"Apraksts",chartDescriptionHintText:"Padoms. R\u0101d\u012bts zem diagrammas",chartType:"Digarammas tips",
barChart:"Joslu diagramma",pieChart:"Sektoru diagramma",polarChart:"Pol\u0101r\u0101 diagramma",dataSeriesField:"Datu s\u0113rijas lauks",labelField:"Kartes teksta lauks",chartColor:"Diagrammas kr\u0101sa",singleColor:"Vienkr\u0101saina",colorByTheme:"T\u0113mas kr\u0101sa",colorByFieldValue:"Lauka v\u0113rt\u012bbas kr\u0101sa",xAxisTitle:"X ass virsraksts",xAxisHintText:"Padoms.\u00a0X ass virsraksts",yAxisTitle:"Y ass virsraksts",yAxisHintText:"Padoms. Y ass virsraksts",fieldColorLabel:"Kartes teksts",
fieldColorColor:"Kr\u0101sa",defaultFieldSelectLabel:"Izv\u0113l\u0113ties",errMsgFieldValuesNotFound:"Nevar atrast v\u0113rt\u012bbas izv\u0113l\u0113tajam laukam",errMsgSectionTitle:"Ievadiet\u00a0sada\u013cas virsrakstu",errMsgFieldByValue:"Izv\u0113lieties lauka v\u0113rt\u012bbu",settingTabTitle:"Iestat\u012bjums",layoutTabTitle:"Izk\u0101rtojums",polarChartSelectFieldsHintText:"Padoms. Atlasiet laukus, lai \u0123ener\u0113tu pol\u0101ro diagrammu",visibilityText:"Redzam\u012bba",fieldNameText:"Lauka nosaukums",
aliasNameText:"Aizst\u0101jv\u0101rds",errMsgPolarFieldsRequired:"Izv\u0113lieties tr\u012bs vai vair\u0101k laukus, lai \u0123ener\u0113tu pol\u0101ro diagrammu",polarChartPolygonFillLabel:"Aizpild\u012bt laukumu",polarChartPolygonFillHintText:"Padoms. Atlasiet izv\u0113les r\u016bti\u0146u, lai pol\u0101raj\u0101 diagramm\u0101 r\u0101d\u012btu laukuma aizpild\u012bjumu",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",
themeDesert:"Desert",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Ireland",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Wetland",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",
themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Visp\u0101r\u012bgie iestat\u012bjumi",locationSymbolLabel:"Grafiskais izvietojuma simbols",locationSymbolHintText:"Padoms.\u00a0Izmanto, lai par\u0101d\u012btu adresi un noklik\u0161\u0137in\u0101tu uz\u00a0izvietojuma",refreshIntervalLabel:"Atjauno\u0161anas interv\u0101ls",refreshIntervalHintText:"Padoms. Izmanto diagrammu atjauno\u0161anai nor\u0101d\u012btaj\u0101 interv\u0101l\u0101. Nor\u0101diet v\u0113rt\u012bbu no\u00a01 l\u012bdz 1440 min\u016bt\u0113m",
errMsgRefreshInterval:"Nor\u0101diet atjauno\u0161anas interv\u0101lu no 0 l\u012bdz 1440 min\u016bt\u0113m",symbolPickerPreviewText:"Priek\u0161skat\u012bjums:"},_localized:{}}});