// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Directions/setting/PresetDestinations.html":'\x3cdiv\x3e\r\n  \x3cspan style\x3d"margin:10px 0 5px 0px;display:inline-block;font-weight:bold;"\x3e${nls.presetDestinations}\x3c/span\x3e\r\n  \x3ctable style\x3d"width:100%;" cellspacing\x3d"0"\x3e\r\n    \x3ctbody\x3e\r\n    \x3ctr\x3e\r\n      \x3ctd style\x3d"width:50%;"\x3e\r\n        \x3ctable style\x3d"width:100%;" cellspacing\x3d"0"\x3e\r\n          \x3ctbody\x3e\r\n          \x3ctr\x3e\r\n            \x3ctd style\x3d"width:200px;"\x3e\r\n              \x3cspan class\x3d"impedance-attribute jimu-ellipsis"\x3e${nls.startPoint}\x3c/span\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd style\x3d"width:auto;"\x3e\r\n              \x3cspan data-dojo-attach-point\x3d"startSearchDom" style\x3d"width:220px;"\x3e\x3c/span\x3e\r\n              \x3cdiv data-dojo-attach-point\x3d"startSearchResultsNode" class\x3d"searchResults arcgisSearch"\x3e\x3c/div\x3e\r\n              \x3c!--\x3cdiv data-dojo-attach-point\x3d"startSearchError" class\x3d"hide preset-des-error"\x3eNo Results\x3c/div\x3e--\x3e\r\n            \x3c/td\x3e\r\n\r\n            \x3ctd style\x3d"width:200px;"\x3e\r\n              \x3cspan class\x3d"impedance-attribute jimu-ellipsis"\x3e${nls.endPoint}\x3c/span\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd style\x3d"width:auto;"\x3e\r\n              \x3cspan data-dojo-attach-point\x3d"endSearchDom" class\x3d"end-search" style\x3d"width:220px;"\x3e\x3c/span\x3e\r\n              \x3cdiv data-dojo-attach-point\x3d"endSearchResultsNode" class\x3d"searchResults arcgisSearch"\x3e\x3c/div\x3e\r\n              \x3c!--\x3cdiv data-dojo-attach-point\x3d"endSearchError" class\x3d"hide preset-des-error"\x3eNo Results\x3c/div\x3e--\x3e\r\n            \x3c/td\x3e\r\n          \x3c/tr\x3e\r\n          \x3c/tbody\x3e\r\n        \x3c/table\x3e\r\n      \x3c/td\x3e\r\n    \x3c/tr\x3e\r\n    \x3c/tbody\x3e\r\n  \x3c/table\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/on dojo/_base/html dojo/query esri/lang esri/tasks/locator dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./PresetDestinations.html esri/dijit/Search jimu/dijit/RadioBtn".split(" "),function(n,d,b,f,h,r,t,u,v,w,x,m){return n([u,v,w],{templateString:x,_defaultLocations:null,_startSearchResults:null,_endSearchResults:null,_isSearchResultsShown:!1,_ERROR_CLASS:"have-error",constructor:function(a){a&&(this._defaultLocations=
a.defaultLocations,this.nls=a.nls)},postCreate:function(){this.inherited(arguments)},startup:function(){this.startSearch=new m({enableSuggestions:!1,enableButtonMode:!1,theme:"arcgisSearch"});this.startSearch.placeAt(this.startSearchDom);this.own(b(this.startSearch,"search-results",d.hitch(this,"_onStartSearchResults")));this.own(b(this.startSearchResultsNode,"li:click",d.hitch(this,"_onSelectStartSearchResult")));this.own(b(this.startSearch.inputNode,"focus",d.hitch(this,"_onCleanStartError")));
this.own(b(this.startSearch.inputNode,"blur",d.hitch(this,function(){!1===this._isSearchResultsShown&&this.startSearch&&this.startSearch.search&&this.startSearch.search()})));this.endSearch=new m({enableSuggestions:!1,enableButtonMode:!1,theme:"arcgisSearch"});this.endSearch.placeAt(this.endSearchDom);this.own(b(this.endSearch,"search-results",d.hitch(this,"_onEndSearchResults")));this.own(b(this.endSearchResultsNode,"li:click",d.hitch(this,"_onSelectEndSearchResult")));this.own(b(this.endSearch.inputNode,
"focus",d.hitch(this,"_onCleanEndError")));this.own(b(this.endSearch.inputNode,"blur",d.hitch(this,function(){!1===this._isSearchResultsShown&&this.endSearch&&this.endSearch.search&&this.endSearch.search()})));this.own(b(window.document,"click",d.hitch(this,function(a){f.isDescendant(a.target,this.searchResultsNode)||this._hideResultMenu()})));if(this._defaultLocations&&this._defaultLocations.length&&0<this._defaultLocations.length)for(var a=0,c=this._defaultLocations.length;a<c;a++)0===a?this.startSearch.set("value",
this.defaultLocations[a]):1===a&&this.endSearch.set("value",this.defaultLocations[a]);this.inherited(arguments)},getValue:function(){var a=[],c=this.startSearch.get("value");a.push(c);c=this.endSearch.get("value");a.push(c);return a},setValue:function(a){a&&0<a.length&&(this._defaultLocations=a)},validate:function(){var a=!1;h(".searchLoading",this.domNode).forEach(d.hitch(this,function(){a=!0}));return!1!==a||f.hasClass(this.startSearch,this._ERROR_CLASS)||f.hasClass(this.endSearch,this._ERROR_CLASS)?
!1:!0},setSources:function(a){a&&a.url&&a.singleLineFieldName?(a={locator:new t(a.url||""),outFields:["*"],singleLineFieldName:a.singleLineFieldName},this.startSearch.set("sources",[a]),this.endSearch.set("sources",[a])):(this.startSearch.set("sources",[]),this.endSearch.set("sources",[]))},_onCleanError:function(a){f.removeClass(a,this._ERROR_CLASS)},_onCleanStartError:function(){this._onCleanError(this.startSearch)},_onCleanEndError:function(){this._onCleanError(this.endSearch)},_onStartSearchResults:function(a){this._onSearchResults(a,
{searchDijit:this.startSearch,searchResultsNode:this.startSearchResultsNode,searchError:this.startSearchError,results:"start"})},_onEndSearchResults:function(a){this._onSearchResults(a,{searchDijit:this.endSearch,searchResultsNode:this.endSearchResultsNode,searchError:this.endSearchError,results:"end"})},_onSearchResults:function(a,c){var p=c.searchDijit.get("sources"),e=c.searchDijit.get("activeSourceIndex"),d=c.searchDijit.get("value"),g="",b=a.results;if(""!==d)if(b&&0<a.numResults){"start"===
c.results?this._startSearchResults=b:"end"===c.results&&(this._endSearchResults=b);var g=g+'\x3cdiv class\x3d"searchMenu searchResultsMenu" role\x3d"menu"\x3e',k;for(k in b)if(b[k]&&b[k].length){var h=p[parseInt(k,10)].name;1<p.length&&"all"===e&&(g+='\x3cdiv title\x3d"'+h+'" class\x3d"menuHeader"\x3e'+h+"\x3c/div\x3e");for(var g=g+"\x3cul\x3e",h=new RegExp("("+d+")","gi"),m=p[k].maxResults||5,l=0,n=b[k].length;l<n&&l<m;l++)var q=r.isDefined(b[k][l].name)?b[k][l].name:this.nls.untitled,g=g+('\x3cli title\x3d"'+
q+'" data-index\x3d"'+l+'" data-source-index\x3d"'+k+'" role\x3d"menuitem" tabindex\x3d"0"\x3e'+q.toString().replace(h,"\x3cstrong \x3e$1\x3c/strong\x3e")+"\x3c/li\x3e");g+="\x3c/url\x3e"}c.searchResultsNode.innerHTML=g+"\x3c/div\x3e";this._showResultMenu(c.searchDijit,c.searchResultsNode);this._resetSelectorPosition(c.searchDijit,".searchResultsMenu")}else f.addClass(c.searchDijit,this._ERROR_CLASS),this._resetSelectorPosition(c.searchDijit,".noResultsMenu")},_onSelectStartSearchResult:function(a){this._onSelectSearchResult(a,
this.startSearch,this._startSearchResults)},_onSelectEndSearchResult:function(a){this._onSelectSearchResult(a,this.endSearch,this._endSearchResults)},_onSelectSearchResult:function(a,c,b){for(a=a.target;!f.hasAttr(a,"data-source-index")||!f.getAttr(a,"data-index");)a=a.parentNode;var e=null,e=f.getAttr(a,"data-source-index");a=parseInt(f.getAttr(a,"data-index"),10);"all"!==e&&(e=parseInt(e,10));b&&b[e]&&b[e][a]&&(e=b[e][a],c.select(e),e.name&&c.set("value",e.name))},_showResultMenu:function(a,c){f.setStyle(c,
"display","block");h(".searchMenu",c).style("display","block");this._isSearchResultsShown=!0;var b=h(".searchInputGroup",a.domNode)[0];b&&(b={width:f.getMarginBox(b).w+"px"},h(".searchMenu",c).style(b))},_resetSelectorPosition:function(a,b){var c=f.getMarginBox(this.domNode.offsetParent);h(b,this.domNode).forEach(d.hitch(this,function(e){var d=f.position(e),g=f.position(a.domNode),g=".noResultsMenu"===b?0:g.h;d.y+d.h>c.h&&f.setStyle(e,"top",-(d.h+g)-4+"px")}))},_hideResultMenu:function(){h(".searchMenu",
this.domNode).style("display","none");this._isSearchResultsShown=!1}})});