// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Nale\u017cy wybra\u0107 co najmniej jeden element.",multiSelectLabelText:"Wybrano element\u00f3w: {num}",_localized:{}},"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Karty",addTab:"Dodaj kart\u0119",layerName:"Warstwa",layerType:"Rodzaj analizy",layerLabel:"Etykieta",actions:"Dzia\u0142ania",closest:"Najbli\u017cszy obiekt",proximity:"Blisko\u015b\u0107",summary:"Podsumowanie",select_lbl:"-- Wybierz --",general_setting_Label:"Ustawienia og\u00f3lne",
units_text_lbl:"Jednostki odleg\u0142o\u015bci",maximum_distance_lbl:"Odleg\u0142o\u015b\u0107 maksymalna najbli\u017cszego obiektu",buffer_text_lbl:"Etykieta buforowania",buffer_lbl:"Odleg\u0142o\u015b\u0107 buforowania",buffer_max_lbl:"Maksymalna odleg\u0142o\u015b\u0107 buforowania",buffer_min_lbl:"Minimalna odleg\u0142o\u015b\u0107 buforowania",routing_checkBox:"W\u0142\u0105cz wyznaczanie tras",weather_Label:"Opcje pogodowe",weather_checkBox:"Do\u0142\u0105cz informacje pogodowe",selectLayers:"wybierz warstwy pogodowe",
currentlySelectedLayer:"Aktualnie wybrane warstwy pogodowe",missingTabLabel:"Brak etykiety w przynajmniej jednej zak\u0142adce",missingLayerInWebMap:"Nie znaleziono warstw operacyjnych.",selectFields:"Wybierz pola",addField:"Dodaj pole",sum:"Sum",min:"Minimum",max:"Maksimum",avg:"\u015arednia",count:"LICZBA",area:"POWIERZCHNIA",length:"D\u0141UGO\u015a\u0106",count_checkBox:"Wy\u015bwietl liczb\u0119 obiekt\u00f3w",area_checkBox:"Wy\u015bwietl sum\u0119 powierzchni",length_checkBox:"Wy\u015bwietl sum\u0119 d\u0142ugo\u015bci",
max_records:"Osi\u0105gni\u0119to limit maksymalny",save_label:"Opcje zapisywania",save_checkbox:"W\u0142\u0105cz zapisywanie",csv_label:"Opcje CSV",csv_checkbox:"Wyeksportuj wszystkie pola w warstwie",display_label:"Opcje wy\u015bwietlania",display_checkbox:"Wy\u015bwietl obiekty podsumowania",snapshot_label:"Opcje migawki",snapshot_checkbox:"W\u0142\u0105cz migawk\u0119",must_select_template:"W opcjach zapisywania wybierz jeden z szablon\u00f3w edycji.",count_label:"Etykieta liczby",area_label:"Etykieta obszaru",
length_label:"Etykieta d\u0142ugo\u015bci",invalid_string_width:"Warto\u015b\u0107 jest za d\u0142uga. ",layer_type_not_supported:"Typ warstwy jest nieobs\u0142ugiwany: ",groupedSummary:"Pogrupowane zliczenia",groupByField:"Pole Grupuj wg",labelType:"Do\u0142\u0105cz etykiet\u0119",prefix:"Jako prefiks",suffix:"Jako sufiks",need_group_field:"U\u017cyj czynno\u015bci edycji, aby zdefiniowa\u0107 pole Grupuj wg.",fieldTitle:"Pole",typeTitle:"Typ",actionsTitle:"Dzia\u0142ania",save_point_checkbox:"Zapisz punkty",
save_line_checkbox:"Zapisz linie",save_poly_checkbox:"Zapisz poligony",no_valid_popup_fields:"Brak prawid\u0142owych p\u00f3l w oknie podr\u0119cznym. U\u017cyj dzia\u0142ania edycji, aby zdefiniowa\u0107 pole.",no_valid_fields:"Brak prawid\u0142owych p\u00f3l. U\u017cyj dzia\u0142ania edycji, aby zdefiniowa\u0107 opcje wy\u015bwietlania.",incident_label:"Etykieta karty",locate_incident_label:"Etykieta obszaru zainteresowania",incident:"Zdarzenie",locate_incident:"Zlokalizuj zdarzenie",buffer_value:"Odleg\u0142o\u015b\u0107 buforowania",
_localized:{}}});