// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dojox/form/nls/CheckedMultiSelect":{invalidMessage:"Se debe seleccionar al menos un elemento.",multiSelectLabelText:"{num} elemento(s) seleccionado(s)",_localized:{}},"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Pesta\u00f1as",addTab:"Agregar pesta\u00f1a",layerName:"Capa",layerType:"Tipo de an\u00e1lisis",layerLabel:"Etiqueta",actions:"Acciones",closest:"Entidad m\u00e1s pr\u00f3xima",proximity:"Proximidad",summary:"Resumen",select_lbl:"-- Seleccionar --",general_setting_Label:"Configuraci\u00f3n general",
units_text_lbl:"Unidades de distancia",maximum_distance_lbl:"Distancia m\u00e1xima a la entidad m\u00e1s pr\u00f3xima",buffer_text_lbl:"Etiqueta de zona de influencia",buffer_lbl:"Distancia de zona de influencia",buffer_max_lbl:"Distancia de zona de influencia m\u00e1xima",buffer_min_lbl:"Distancia de zona de influencia m\u00ednima",routing_checkBox:"Habilitar enrutamiento",weather_Label:"Opciones del tiempo",weather_checkBox:"Incluir informaci\u00f3n del tiempo",selectLayers:"seleccionar capas de tiempo",
currentlySelectedLayer:"Capas del tiempo seleccionadas actualmente",missingTabLabel:"Falta la etiqueta en una pesta\u00f1a al menos",missingLayerInWebMap:"No se ha encontrado ninguna capa operativa.",selectFields:"Selecciona campos",addField:"Agregar campo",sum:"Suma",min:"M\u00ednimo",max:"M\u00e1ximo",avg:"Media",count:"TOTAL",area:"\u00c1REA",length:"LONGITUD",count_checkBox:"Mostrar recuento de entidades",area_checkBox:"Mostrar suma de \u00e1rea",length_checkBox:"Mostrar suma de longitud",max_records:"Se ha alcanzado el l\u00edmite m\u00e1ximo",
save_label:"Opciones para guardar",save_checkbox:"Habilitar guardar",csv_label:"Opciones de CSV",csv_checkbox:"Exportar todos los campos de la capa",display_label:"Opciones de visualizaci\u00f3n",display_checkbox:"Mostrar entidades de resumen",snapshot_label:"Opciones de instant\u00e1nea",snapshot_checkbox:"Habilitar instant\u00e1nea",must_select_template:"Selecciona una de las plantillas de edici\u00f3n en Opciones para guardar.",count_label:"Etiqueta de recuento",area_label:"Etiqueta de \u00e1rea",
length_label:"Etiqueta de longitud",invalid_string_width:"El valor es demasiado largo. ",layer_type_not_supported:"El tipo de capa no es compatible: ",groupedSummary:"Recuentos agrupados",groupByField:"Agrupar por campo",labelType:"Adjuntar etiqueta",prefix:"Como prefijo",suffix:"Como sufijo",need_group_field:"Use la acci\u00f3n Editar para definir Agrupar por campo.",fieldTitle:"Campo",typeTitle:"Tipo",actionsTitle:"Acciones",save_point_checkbox:"Guardar puntos",save_line_checkbox:"Guardar l\u00edneas",
save_poly_checkbox:"Guardar pol\u00edgonos",no_valid_popup_fields:"No hay campos v\u00e1lidos en el elemento emergente. Utilice la acci\u00f3n editar para definir un campo.",no_valid_fields:"No hay campos v\u00e1lidos. Utilice la acci\u00f3n editar para definir las opciones de visualizaci\u00f3n.",incident_label:"Etiqueta de pesta\u00f1a",locate_incident_label:"Etiqueta de \u00e1rea de inter\u00e9s",incident:"Incidente",locate_incident:"Localizar incidente",buffer_value:"Distancia de zona de influencia",
_localized:{}}});