// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/LayerList/LayerListView.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"layer-list-operations" data-dojo-attach-point\x3d"layerListOperations"\x3e\r\n    \x3c!--div class\x3d"setting-image jimu-icon jimu-icon-setting jimu-state-disabled"\x3e\x3c/div--\x3e\r\n  \x3c/div\x3e\r\n  \x3ctable class\x3d"layer-list-table"\x3e\r\n    \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"layerListTable"\x3e\x3c/tbody\x3e\r\n    \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"tableListTable"\x3e\x3c/tbody\x3e       \r\n  \x3c/table\x3e\r\n\x3c/div\x3e\r\n'}});
define("dijit/_WidgetBase dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/on dojo/query jimu/dijit/CheckBox jimu/dijit/DropMenu ./PopupMenu dijit/_TemplatedMixin dojo/text!./LayerListView.html dojo/dom-class dojo/dom-style ./NlsStrings".split(" "),function(q,r,l,h,f,m,g,t,u,v,w,x,k,n,y){return r([q,w],{templateString:x,_currentSelectedLayerRowNode:null,operationsDropMenu:null,postMixInProperties:function(){this.inherited(arguments);this.nls=y.value},postCreate:function(){h.forEach(this.operLayerInfos.getLayerInfoArray(),
function(a){this.drawListNode(a,0,this.layerListTable,!0)},this);h.forEach(this.operLayerInfos.getTableInfoArray(),function(a){this.drawListNode(a,0,this.tableListTable,!0)},this);this._initOperations()},drawListNode:function(a,b,c){var d;this.isLayerHiddenInWidget(a)||(0===a.newSubLayers.length?(d=this.addLayerNode(a,b,c),this.config.showLegend?this.addLegendNode(a,b,d.subNode):(a=g(".showLegend-div",d.currentNode)[0])&&k.add(a,"hidden")):(d=this.addLayerNode(a,b,c),h.forEach(a.newSubLayers,l.hitch(this,
function(a,b){this.drawListNode(b,a+1,d.subNode)},b))))},addLayerNode:function(a,b,c){var d=f.create("tr",{"class":"jimu-widget-row layer-row ",layerTrNodeId:a.id},c),e,p,g,k,h;e=f.create("td",{"class":"col col1"},d);for(g=0;g<b;g++)f.create("div",{"class":"begin-blank-div jimu-float-leading",innerHTML:""},e);h=f.create("div",{"class":"showLegend-div jimu-float-leading",imageShowLegendDivId:a.id},e);p=f.create("div",{"class":"div-select jimu-float-leading"},e);g=new t({checked:a.isVisible(),"class":"visible-checkbox-"+
a.id});f.place(g.domNode,p);k=f.create("div",{"class":"noLegend-div jimu-float-leading"},e);f.create("img",{"class":"noLegend-image",src:this.layerListWidget.folderUrl+(a.isTable?"images/table.png":"images/noLegend.png"),alt:"l"},k);if(a.noLegend||a.isTable)n.set(h,"display","none"),n.set(p,"display","none"),n.set(k,"display","block");n.set(e,"width",12*b+40+"px");b=f.create("td",{"class":"col col2"},d);e="";try{a.isInScale()||(e="grayed-title")}catch(z){console.warn(z.message)}f.create("div",{innerHTML:a.title,
"class":"layer-title-div-"+a.id+" div-content jimu-float-leading "+e},b);e=f.create("td",{"class":"col col3"},d);e=f.create("div",{"class":"layers-list-popupMenu-div"},e);p=(new v({_layerInfo:a,box:this.layerListWidget.domNode.parentNode,popupMenuNode:e,layerListWidget:this.layerListWidget,_config:this.config})).placeAt(e);this.own(m(p,"onMenuClick",l.hitch(this,this._onPopupMenuItemClick,a,p)));c=f.create("tr",{"class":"",layerContentTrNodeId:a.id},c);c=f.create("td",{"class":"",colspan:"3"},c);
c=f.create("table",{"class":"layer-sub-node",subNodeId:a.id},c);this.own(m(b,"click",l.hitch(this,this._onRowTrClick,a,h,d,c)));this.own(m(h,"click",l.hitch(this,this._onRowTrClick,a,h,d,c)));this.own(m(d,"mouseover",l.hitch(this,this._onLayerNodeMouseover,d,p)));this.own(m(d,"mouseout",l.hitch(this,this._onLayerNodeMouseout,d,p)));this.own(m(g.domNode,"click",l.hitch(this,this._onCkSelectNodeClick,a,g)));this.own(m(e,"click",l.hitch(this,this._onPopupMenuClick,a,p,d)));return{currentNode:d,subNode:c}},
addLegendNode:function(a,b,c){c=f.create("tr",{"class":"legend-node-tr"},c);c=f.create("td",{"class":"legend-node-td"},c);try{var d=a.createLegendsNode();n.set(d,"font-size",12*(b+1)+"px");f.place(d,c)}catch(e){console.error(e)}},_foldSwitch:function(a,b,c){return"none"===n.get(c,"display")?this._foldOrUnfoldLayer(a,!1,b,c):this._foldOrUnfoldLayer(a,!0,b,c)},_foldOrUnfoldLayer:function(a,b,c,d){var e=e?c:g("div[imageShowLegendDivId\x3d'"+a.id+"']",this.layerListTable)[0],f=f?d:g("table[subNodeId\x3d'"+
a.id+"']",this.layerListTable)[0];c=null;e&&f&&(b?(n.set(f,"display","none"),k.remove(e,"unfold"),c=!0):(n.set(f,"display","table"),k.add(e,"unfold"),c=!1,a.isLeaf()&&(b=g(".legends-div",f)[0],e=g(".legends-loading-img",b)[0],b&&e&&a.drawLegends(b,this.layerListWidget.appConfig.portalUrl))));return c},redrawLegends:function(a){var b=g("div[legendsDivId\x3d'"+a.id+"']",this.layerListTable)[0];b&&(b._legendDijit&&b._legendDijit.destroy&&b._legendDijit.destroy(),a.drawLegends(b,this.layerListWidget.appConfig.portalUrl))},
_foldOrUnfoldLayers:function(a,b){h.forEach(a,function(a){this._foldOrUnfoldLayer(a,b)},this)},_onCkSelectNodeClick:function(a,b,c){c.ctrlKey||c.metaKey?a.isRootLayer()?this.turnAllRootLayers(b.checked):this.turnAllSameLevelLayers(a,b.checked):a.setTopLayerVisible(b.checked);c.stopPropagation()},_onPopupMenuClick:function(a,b,c,d){this._changeSelectedLayerRow(c);b&&"opened"===b.state?b.closeDropMenu():(this._hideCurrentPopupMenu(),b&&(this.currentPopupMenu=b,b.openDropMenu()));this.operationsDropMenu&&
"opened"===this.operationsDropMenu.state&&this.operationsDropMenu.closeDropMenu();d.stopPropagation()},_hideCurrentPopupMenu:function(){this.currentPopupMenu&&"opened"===this.currentPopupMenu.state&&this.currentPopupMenu.closeDropMenu()},_onLayerNodeMouseover:function(a){k.add(a,"layer-row-mouseover")},_onLayerNodeMouseout:function(a){k.remove(a,"layer-row-mouseover")},_onLayerListWidgetPaneClick:function(){this.operationsDropMenu&&this.operationsDropMenu.closeDropMenu()},_onRowTrClick:function(a,
b,c,d,e){this._changeSelectedLayerRow(c);b=this._foldSwitch(a,b,d);if(e.ctrlKey||e.metaKey)a.isRootLayer()?this.foldOrUnfoldAllRootLayers(b):this.foldOrUnfoldSameLevelLayers(a,b)},_changeSelectedLayerRow:function(a){this._currentSelectedLayerRowNode&&this._currentSelectedLayerRowNode===a||(this._currentSelectedLayerRowNode&&k.remove(this._currentSelectedLayerRowNode,"jimu-widget-row-selected"),k.add(a,"jimu-widget-row-selected"),this._currentSelectedLayerRowNode=a)},_onPopupMenuItemClick:function(a,
b,c,d){d={itemKey:c.key,extraData:d,layerListWidget:this.layerListWidget,layerListView:this};"transparency"===c.key?"none"===n.get(b.transparencyDiv,"display")?b.showTransNode(a.getOpacity()):b.hideTransNode():(a=b.popupMenuInfo.onPopupMenuClick(d),a.closeMenu&&b.closeDropMenu())},_exchangeLayerTrNode:function(a,b){var c=g("tr[layerTrNodeId\x3d'"+a.id+"']",this.layerListTable)[0],d=g("tr[layerTrNodeId\x3d'"+b.id+"']",this.layerListTable)[0],e=g("tr[layerContentTrNodeId\x3d'"+b.id+"']",this.layerListTable)[0];
c&&d&&e&&(this.layerListTable.removeChild(d),this.layerListTable.insertBefore(d,c),this.layerListTable.removeChild(e),this.layerListTable.insertBefore(e,c))},_getMovedSteps:function(a,b){var c=1,d,e=this.operLayerInfos.getLayerInfoArray();h.forEach(e,function(b,c){a.id===b.id&&(d=c)},this);if("moveup"===b)for(;!e[d].isFirst;)if(d--,this.isLayerHiddenInWidget(e[d])&&!e[d].isFirst)c++;else break;else for(;!e[d].isLast;)if(d++,this.isLayerHiddenInWidget(e[d])&&!e[d].isLast)c++;else break;return c},_initOperations:function(){this.operationsDropMenu=
(new u({items:[{key:"turnAllLayersOn",label:this.nls.turnAllLayersOn},{key:"turnAllLayersOff",label:this.nls.turnAllLayersOff},{key:"separator"},{key:"expandAllLayers",label:this.nls.expandAllLayers},{key:"collapseAlllayers",label:this.nls.collapseAlllayers}],box:this.layerListWidget.domNode.parentNode})).placeAt(this.layerListOperations);var a=g("div.jimu-dropmenu \x3e div:first-child",this.layerListOperations)[0];a&&(k.remove(a,["jimu-icon-btn","popup-menu-button"]),k.add(a,["feature-action","icon-operation"]));
this.operationsDropMenu.btnNode&&this.own(m(this.operationsDropMenu.btnNode,"click",l.hitch(this,this._onLayerListOperationsClick)));this.own(m(this.operationsDropMenu,"onMenuClick",l.hitch(this,this._onOperationsMenuItemClick)))},_onLayerListOperationsClick:function(){this._hideCurrentPopupMenu()},_onOperationsMenuItemClick:function(a){switch(a.key){case "turnAllLayersOn":this.turnAllRootLayers(!0);break;case "turnAllLayersOff":this.turnAllRootLayers(!1);break;case "expandAllLayers":this.foldOrUnfoldAllRootLayers(!1);
break;case "collapseAlllayers":this.foldOrUnfoldAllRootLayers(!0)}},isFirstDisplayedLayerInfo:function(a){var b,c;a.isFirst||!a.isRootLayer()?b=!0:(b=this._getMovedSteps(a,"moveup"),c=this.operLayerInfos.getLayerInfoArray(),a=this.operLayerInfos._getTopLayerInfoIndexById(a.id),b=this.isLayerHiddenInWidget(c[a-b])?!0:!1);return b},isLastDisplayedLayerInfo:function(a){var b,c;a.isLast||!a.isRootLayer()?b=!0:(b=this._getMovedSteps(a,"movedown"),c=this.operLayerInfos.getLayerInfoArray(),a=this.operLayerInfos._getTopLayerInfoIndexById(a.id),
b=this.isLayerHiddenInWidget(c[a+b])?!0:!1);return b},moveUpLayer:function(a){var b=this._getMovedSteps(a,"moveup");this.layerListWidget._denyLayerInfosReorderResponseOneTime=!0;(b=this.operLayerInfos.moveUpLayer(a,b))&&this._exchangeLayerTrNode(b,a)},moveDownLayer:function(a){var b=this._getMovedSteps(a,"movedown");this.layerListWidget._denyLayerInfosReorderResponseOneTime=!0;(b=this.operLayerInfos.moveDownLayer(a,b))&&this._exchangeLayerTrNode(a,b)},isLayerHiddenInWidget:function(a){var b=!1,c=
a;if(a&&this.config.layerOptions&&void 0!==this.config.layerOptions[a.id])for(;c&&!(b=b||!this.config.layerOptions[c.id].display);)c=c.parentLayerInfo;else b=!1;return b},turnAllRootLayers:function(a){var b=this.operLayerInfos.getLayerInfoArray();h.forEach(b,function(b){this.isLayerHiddenInWidget(b)||b.setTopLayerVisible(a)},this)},turnAllSameLevelLayers:function(a,b){var c={},d=a.getRootLayerInfo();d.traversal(l.hitch(this,function(d){d.parentLayerInfo&&d.parentLayerInfo.id===a.parentLayerInfo.id&&
!this.isLayerHiddenInWidget(d)?c[d.id]={visible:b}:c[d.id]={visible:d.isVisible()}}));d.resetLayerObjectVisibility(c)},foldOrUnfoldAllRootLayers:function(a){var b=h.filter(this.operLayerInfos.getLayerInfoArray(),function(a){return!this.isLayerHiddenInWidget(a)},this);this._foldOrUnfoldLayers(b,a)},foldOrUnfoldSameLevelLayers:function(a,b){var c;a.parentLayerInfo&&(c=h.filter(a.parentLayerInfo.getSubLayers(),function(a){return!this.isLayerHiddenInWidget(a)},this),this._foldOrUnfoldLayers(c,b))}})});