// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/Deferred dojo/promise/all jimu/WidgetManager esri/lang esri/graphicsUtils ./NlsStrings".split(" "),function(m,k,e,l,n,p,f,q,r){var h=m([],{_candidateMenuItems:null,_displayItems:null,_layerInfo:null,_layerType:null,_appConfig:null,constructor:function(b,a,c,g){this.nls=r.value;this._layerInfo=b;this._layerType=c;this.layerListWidget=g;this._initCandidateMenuItems();this._initDisplayItems(a)},_getATagLabel:function(){var b,a;b=this._layerInfo.isItemLayer&&
this._layerInfo.isItemLayer();a=this._layerInfo.getUrl();b?(b=this._layerInfo._getItemDetailsPageUrl()||a,a=this.nls.itemShowItemDetails):!a||"CSVLayer"!==this._layerType&&"KMLLayer"!==this._layerType?(b=a&&"WMSLayer"===this._layerType?a+(-1<a.indexOf("?")?"\x26":"?")+"SERVICE\x3dWMS\x26REQUEST\x3dGetCapabilities":a&&"WFSLayer"===this._layerType?a+(-1<a.indexOf("?")?"\x26":"?")+"SERVICE\x3dWFS\x26REQUEST\x3dGetCapabilities":a?a:"",a=this.nls.itemDesc):(b=a,a=this.nls.itemDownload);return'\x3ca class\x3d"menu-item-description" target\x3d"_blank" href\x3d"'+
b+'"\x3e'+a+"\x3c/a\x3e"},_initCandidateMenuItems:function(){this._candidateMenuItems=[{key:"separator",label:""},{key:"empty",label:this.nls.empty},{key:"zoomto",label:this.nls.itemZoomTo},{key:"transparency",label:this.nls.itemTransparency},{key:"moveup",label:this.nls.itemMoveUp},{key:"movedown",label:this.nls.itemMoveDown},{key:"table",label:this.nls.itemToAttributeTable},{key:"controlPopup",label:this.nls.removePopup},{key:"controlLabels",label:this.nls.showLabels},{key:"url",label:this._getATagLabel()}]},
_initDisplayItems:function(b){this._displayItems=[];k.forEach(b,function(a){k.forEach(this._candidateMenuItems,function(b){a.key===b.key&&(this._displayItems.push(e.clone(b)),a.onClick&&(this._displayItem.onClick=a.onClick))},this)},this)},_isSupportedByAT:function(){return!0},_isSupportedByAT_bk:function(b,a){var c;c=b.config;c=0===c.layerInfos.length?!0:k.some(c.layerInfos,function(a){if(a.id===this._layerInfo.id&&a.show)return!0},this);return a.isSupportedLayer&&a.isSupportQuery&&!a.otherReasonCanNotSupport&&
c?!0:!1},getDeniedItems:function(){var b=new l,a=[];this.layerListWidget.layerListView.isFirstDisplayedLayerInfo(this._layerInfo)&&a.push({key:"moveup",denyType:"disable"});this.layerListWidget.layerListView.isLastDisplayedLayerInfo(this._layerInfo)&&a.push({key:"movedown",denyType:"disable"});this._layerInfo.getUrl()||a.push({key:"url",denyType:"disable"});this._layerInfo.canShowLabel()||a.push({key:"controlLabels",denyType:"hidden"});var c=this._layerInfo.loadInfoTemplate(),g=this._layerInfo.getSupportTableInfo();
n({infoTemplate:c,supportTableInfo:g}).then(e.hitch(this,function(c){c.infoTemplate||a.push({key:"controlPopup",denyType:"disable"});c=c.supportTableInfo;var d=this.layerListWidget.appConfig.getConfigElementsByName("AttributeTable")[0];d&&d.visible?this._isSupportedByAT(d,c)||(this._layerInfo.parentLayerInfo&&this._layerInfo.parentLayerInfo.isMapNotesLayerInfo()?a.push({key:"table",denyType:"hidden"}):a.push({key:"table",denyType:"disable"})):a.push({key:"table",denyType:"hidden"});b.resolve(a)}),
function(){b.resolve(a)});return b},getDisplayItems:function(){return this._displayItems},onPopupMenuClick:function(b){var a={closeMenu:!0};switch(b.itemKey){case "zoomto":this._onItemZoomToClick(b);break;case "moveup":this._onMoveUpItemClick(b);break;case "movedown":this._onMoveDownItemClick(b);break;case "table":this._onTableItemClick(b);break;case "transparencyChanged":this._onTransparencyChanged(b);a.closeMenu=!1;break;case "controlPopup":this._onControlPopup();break;case "controlLabels":this._onControlLabels()}return a},
_onItemZoomToClick:function(b){this._layerInfo.getExtent().then(e.hitch(this,function(a){var b=null;a=a&&0<a.length&&a[0];this._isValidExtent(a)&&(b=a);b?this._layerInfo.map.setExtent(b):0<=this._layerInfo.map.graphicsLayerIds.indexOf(this._layerInfo.id)&&this._layerInfo.getLayerObject().then(e.hitch(this,function(a){if(a.graphics&&0<a.graphics.length){try{b=q.graphicsExtent(a.graphics)}catch(t){console.error(t)}b&&this._layerInfo.map.setExtent(b)}}))}))},_isValidExtent:function(b){var a=!1;f.isDefined(b)&&
f.isDefined(b.xmin)&&isFinite(b.xmin)&&f.isDefined(b.ymin)&&isFinite(b.ymin)&&f.isDefined(b.xmax)&&isFinite(b.xmax)&&f.isDefined(b.ymax)&&isFinite(b.ymax)&&(a=!0);return a},_onMoveUpItemClick:function(b){this._layerInfo.isFirst||b.layerListView.moveUpLayer(this._layerInfo)},_onMoveDownItemClick:function(b){this._layerInfo.isLast||b.layerListView.moveDownLayer(this._layerInfo)},_onTableItemClick:function(b){this._layerInfo.getSupportTableInfo().then(e.hitch(this,function(a){var c=this.layerListWidget.appConfig.getConfigElementsByName("AttributeTable")[0];
this._isSupportedByAT(c,a)&&(a=p.getInstance(),a.triggerWidgetOpen(c.id).then(e.hitch(this,function(){b.layerListWidget.publishData({target:"AttributeTable",layer:this._layerInfo})})))}))},_onTransparencyChanged:function(b){this._layerInfo.setOpacity(1-b.extraData.newTransValue)},_onControlPopup:function(b){this._layerInfo.controlPopupInfo.enablePopup?this._layerInfo.disablePopup():this._layerInfo.enablePopup();this._layerInfo.map.infoWindow.hide()},_onControlLabels:function(b){this._layerInfo.canShowLabel()&&
(this._layerInfo.isShowLabels()?this._layerInfo.hideLabels():this._layerInfo.showLabels())}});h.create=function(b,a){var c=new l,g=b.isRootLayer(),f={RootLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"moveup"},{key:"movedown"},{key:"separator"},{key:"url"}],RootLayerAndFeatureLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"controlPopup"},{key:"separator"},{key:"controlLabels"},{key:"separator"},{key:"moveup"},{key:"movedown"},{key:"separator"},{key:"table"},
{key:"separator"},{key:"url"}],FeatureLayer:[{key:"controlPopup"},{key:"separator"},{key:"table"},{key:"separator"},{key:"url"}],GroupLayer:[{key:"url"}],Table:[{key:"table"},{key:"separator"},{key:"url"}],"default":[{key:"url",onClick:null}]};b.getLayerType().then(e.hitch(this,function(d){var e="",e=!g||"FeatureLayer"!==d&&"CSVLayer"!==d&&"ArcGISImageServiceLayer"!==d&&"StreamLayer"!==d&&"ArcGISImageServiceVectorLayer"!==d?g?"RootLayer":"FeatureLayer"===d||"CSVLayer"===d?"FeatureLayer":"GroupLayer"===
d?"GroupLayer":"Table"===d?"Table":"default":"RootLayerAndFeatureLayer";c.resolve(new h(b,f[e],d,a))}),e.hitch(this,function(){c.resolve(new h(b,[{key:"empty"}]))}));return c};return h});