// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Deferred dojo/promise/all esri/lang jimu/portalUrlUtils ./table/_FeatureTable ./utils".split(" "),function(r,f,l,m,t,n,q,u,p){return r(null,{_activeLayerInfoId:null,_activeRelationshipKey:null,nls:null,config:null,map:null,_delayedLayerInfos:[],_layerInfosFromMap:[],featureTableSet:{},relationshipsSet:{},relationshipTableSet:{},currentRelationshipKey:null,constructor:function(a){this.map=a&&a.map;this.nls=a&&a.nls;this._delayedLayerInfos=
[];this._layerInfosFromMap=[];this.featureTableSet={};this.relationshipsSet={};this.relationshipTableSet={};this.currentRelationshipKey=null},setConfig:function(a){this.config=f.clone(a||{})},setMap:function(a){this.map=a},updateLayerInfoResources:function(a){var b=new m;p.readConfigLayerInfosFromMap(this.map,!1,!0).then(f.hitch(this,function(d){this._layerInfosFromMap=d;this._processDelayedLayerInfos();a&&(0===this.config.layerInfos.length?(d=p.getConfigInfosFromLayerInfos(d),this.config.layerInfos=
l.filter(d,function(a){return a.show})):this.config.layerInfos=l.filter(f.delegate(this.config.layerInfos),f.hitch(this,function(a){var b=this._getLayerInfoById(a.id);return a.show&&b&&(a.name=b.name||b.title)})));b.resolve()}),function(a){b.reject(a)});return b},isEmpty:function(){return this.config&&this.config.layerInfos&&0>=this.config.layerInfos.length},getConfigInfos:function(){return f.clone(this.config.layerInfos)},addLayerInfo:function(a){0===this._layerInfosFromMap.length?this._delayedLayerInfos.push(a):
0<this._layerInfosFromMap.length&&!this._getLayerInfoById(a.id)&&this._layerInfosFromMap.push(a)},addConfigInfo:function(a){this._getConfigInfoById(a.id)||(a=p.getConfigInfoFromLayerInfo(a),this.config.layerInfos.push({id:a.id,name:a.name,layer:{url:a.layer.url,fields:a.layer.fields}}))},removeLayerInfo:function(a){a=this._getLayerInfoById(a);a=this._layerInfosFromMap.indexOf(a);this._layerInfosFromMap.splice(a,1)},removeConfigInfo:function(a){if(f.getObject("config.layerInfos",!1,this))for(var b=
this.config.layerInfos.length,d=0;d<b;d++)if(this.config.layerInfos[d].id===a){this.featureTableSet[a]&&(this.featureTableSet[a].destroy(),delete this.featureTableSet[a]);this.config.layerInfos.splice(d,1);break}},getQueryTable:function(a,b,d){var c=new m;this._activeLayerInfoId=a;this.featureTableSet[a]?c.resolve({isSupportQuery:!0,table:this.featureTableSet[a]}):this._getQueryTableInfo(a).then(f.hitch(this,function(e){if(e){var g=e.layerInfo,k=e.layerObject;e=e.tableInfo;if(this.featureTableSet[a])c.resolve({isSupportQuery:e.isSupportQuery,
table:this.featureTableSet[a]});else if(f.getObject("isSupportQuery",!1,e)){var h=this._getConfigInfoById(a);h||(this.addConfigInfo(g),h=this._getConfigInfoById(a));var v=f.getObject("layer.fields",!1,h);h.layer.fields=this._clipValidFields(v,k&&k.fields);g=new u({map:this.map,matchingMap:b,hideExportButton:d,layerInfo:g,configedInfo:h,nls:this.nls});this.featureTableSet[a]=g;c.resolve({isSupportQuery:e.isSupportQuery,table:g})}else c.resolve({isSupportQuery:!1})}else c.resolve(null)}),function(a){c.reject(a)});
return c},getRelationTable:function(a,b,d,c){var e=new m,g=this.relationshipsSet[b];this._activeRelationshipKey=b;if(g){var k=this._getLayerInfoById(a);a=f.getObject("shipInfo.id",!1,g);this.getQueryTable(a,d,c).then(f.hitch(this,function(a){if(a&&a.table){var b=a.table;b.set("relatedOriginalInfo",k);b.set("relationship",g)}e.resolve(a)}),f.hitch(function(){e.resolve(null)}))}else e.resolve(null);return e},removeRelationTable:function(a){this.relationshipTableSet[a]&&(this.relationshipTableSet[a].destroy(),
this.relationshipTableSet[a]=null)},getCurrentTable:function(a){return this.featureTableSet[a]||this.relationshipTableSet[a]},collectRelationShips:function(a,b){this._collectRelationShips(a,a.layerObject,b)},getConfigInfoById:function(a){return this._getConfigInfoById(a)},getLayerInfoById:function(a){return this._getLayerInfoById(a)},getRelationshipsByInfoId:function(a){var b=[],d;for(d in this.relationshipsSet){var c=this.relationshipsSet[d];c._layerInfoId===a&&b.push(c)}return b},empty:function(){this._delayedLayerInfos=
[];this._layerInfosFromMap=[];this.featureTableSet={};for(var a in this.relationshipsSet)this.relationshipsSet[a].shipInfo=null;this.relationshipsSet={};this.relationshipTableSet={};this.nls=this.map=this.config=this.currentRelationshipKey=null},_processDelayedLayerInfos:function(){0<this._delayedLayerInfos.length&&(l.forEach(this._delayedLayerInfos,f.hitch(this,function(a){!this._getLayerInfoById(a&&a.id)&&this.map&&this.map.getLayer(a.id)&&this._layerInfosFromMap.push(a)})),this._delayedLayerInfos=
[])},_getLayerInfoById:function(a){for(var b=0,d=this._layerInfosFromMap.length;b<d;b++)if(this._layerInfosFromMap[b]&&this._layerInfosFromMap[b].id===a)return this._layerInfosFromMap[b]},_getConfigInfoById:function(a){if(!f.getObject("layerInfos.length",!1,this.config))return null;for(var b=0,d=this.config.layerInfos.length;b<d;b++){var c=this.config.layerInfos[b];if(c&&c.id===a)return c}return null},_getQueryTableInfo:function(a){var b=new m,d=this._getLayerInfoById(a);if(d){var c=[],e=d.getUrl();
c.push(d.getLayerObject());c.push(d.getSupportTableInfo());e&&c.push(d.getRelatedTableInfoArray());t(c).then(f.hitch(this,function(c){if(this._activeLayerInfoId===a&&c){var g=c[0],f=c[1];c=e?c[2]:[];n.isDefined(c)&&n.isDefined(g)&&0<c.length&&this._collectRelationShips(d,g,c);b.resolve({layerInfo:d,layerObject:g,tableInfo:f})}else b.resolve(null)}),function(a){b.reject(a)})}else console.error("no activeLayerInfo!"),b.reject(Error());return b},_collectRelationShips:function(a,b,d){var c=b.relationships;
if(c&&0<c.length&&b&&b.url){var e=b.url.split("/");l.forEach(c,f.hitch(this,function(c){e[e.length-1]=c.relatedTableId;var g=e.join("/"),h=l.filter(d,f.hitch(this,function(a){a=a.getUrl();return n.isDefined(a)&&n.isDefined(g)&&q.removeProtocol(a.toString().toLowerCase())===q.removeProtocol(g.toString().toLowerCase())}));h&&0<h.length&&(c.shipInfo=h[0]);h=a.id+"_"+c.name+"_"+c.id;c._relKey=h;c._layerInfoId=a.id;this.relationshipsSet[h]||(this.relationshipsSet[h]=c,this.relationshipsSet[h].objectIdField=
b.objectIdField)}))}},_getLayerInfoLabel:function(a){return a.name||a.title},_getLayerInfoId:function(a){return a&&a.id||""},_clipValidFields:function(a,b){if(!a||!a.length)return b||[];if(!b||!b.length)return a;for(var d=[],c=0,e=a.length;c<e;c++)for(var g=a[c],k=0,h=b.length;k<h;k++)if(b[k].name===g.name){d.push(g);break}0===d.length&&0<a.length&&(c=f.clone(b),l.forEach(c,f.hitch(this,function(a){"esriFieldTypeGeometry"!==a.type&&(a.show=!0,d.push(a))})));return d}})});