// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/dom-construct dojo/query dijit/_WidgetBase dijit/_TemplatedMixin jimu/dijit/ViewStack dojox/gesture/swipe dojox/gesture/tap jimu/utils".split(" "),function(q,l,r,f,m,e,n,t,u,v,w,x,p){var k=0;return q([t,u],{baseClass:"jimu-header-more-popup",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"pages" data-dojo-attach-point\x3d"pagesNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"points jimu-corner-bottom"\x3e\x3cdiv class\x3d"points-inner"data-dojo-attach-point\x3d"pointsNode"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
margin:4,postCreate:function(){this.nodes=[];this.pages=[];this.createCloseBtn()},startup:function(){this.viewStack=new v({views:[],viewType:"dom"},this.pagesNode);this.viewStack.startup();m(this.pagesNode,w.end,l.hitch(this,function(a){k<this.maximumPages-1&&a.dx&&0>a.dx?(k++,this._selectPage(k)):a.dx&&0<a.dx&&0<k&&(k--,this._selectPage(k))}));this.resize()},resize:function(){var a=this._calculateGridParam(),d;null!==a?(f.setStyle(this.domNode,p.getPositionStyle(a.position)),this.nodeWidth=a.cellSize-
this.margin,this.oldGridParam&&this.oldGridParam.rows===a.rows&&this.oldGridParam.cols===a.cols||(this.clearPages(),this.createPages(a)),this.nodes.forEach(l.hitch(this,function(b,c){this.setItemNodePosition(b,c,a)})),this.oldGridParam=a,d=n("div.close",this.domNode)[0],f.setStyle(d,{width:.25*this.nodeWidth+"px",height:.25*this.nodeWidth+"px"})):(this.oldGridParam=null,f.setStyle(this.domNode,p.getPositionStyle({left:0,top:0,width:0,height:0,zIndex:111})),this.nodeWidth=0);!window.appInfo.isRunInMobile&&
760<window.innerWidth&&this.numWidget&&8>=this.numWidget.length&&this.hide()},setItemNodePosition:function(a,d,b){var c,g,h=48,e=16;c=0===d%b.cols?0:this.margin/2;g=d%(b.rows*b.cols)<b.cols?0:this.margin/2;d={};"number"===typeof this.nodeWidth&&(d.width=this.nodeWidth+"px",d.height=this.nodeWidth+"px");"number"===typeof c&&(window.isRTL?d.marginRight=c+"px":d.marginLeft=c+"px");"number"===typeof g&&(d.marginTop=g+"px");if(c=n("img",a)[0])b.iconScaled&&(h*=this.nodeWidth/120),f.setStyle(c,{width:h+
"px",height:h+"px"});if(h=n("div.node-label",a)[0])b.showLabel?(b.iconScaled&&(e*=this.nodeWidth/120),f.setStyle(h,{"font-size":e+"px",display:"block"})):f.setStyle(h,{"font-size":e+"px",display:"none"});f.setStyle(a,d)},clearPages:function(){r.forEach(this.pages,function(a){this.viewStack.removeView(a.pageNode)},this);e.empty(this.pointsNode);this.pages=[];this.nodes=[]},createPages:function(a){var d,b,c,g;this.maximumPages=d=Math.ceil(this.items.length/(a.rows*a.cols));for(b=0;b<d;b++)c=e.create("div",
{"class":"page"}),this.createPageItems(b,c,a),this.viewStack.addView(c),1<d&&(g=e.create("div",{"class":"point"},this.pointsNode),this.own(m(g,"click",l.hitch(this,this._onPageNodeClick,b)))),this.pages.push({pageNode:c,pointNode:g});0<this.viewStack.views.length&&this._selectPage(0)},_onPageNodeClick:function(a){this._selectPage(a)},_selectPage:function(a){1<this.pages.length&&(n(".point",this.domNode).removeClass("point-selected  jimu-main-background"),f.addClass(this.pages[a].pointNode,"point-selected jimu-main-background"));
this.viewStack.switchView(this.pages[a].pageNode)},createPageItems:function(a,d,b){var c,g,e;c=this.items.length;g=b.rows*b.cols;b=(a+1)*g;e=b-c;b=Math.min(b,c);for(a*=g;a<b;a++)this.createItemNode(a,d);for(a=c;a<c+e;a++)this.createEmptyItemNode(d)},createItemNode:function(a,d){var b,c;c=this.items[a];b=e.create("div",{"class":"icon-node jimu-float-leading jimu-main-background",title:c.label,settingId:c.id},d);e.create("img",{src:c.icon},b);e.create("div",{"class":"node-label",title:c.label,innerHTML:p.stripHTML(c.label)},
b);b.config=c;this.own(m(b,x,l.hitch(this,function(){this.onNodeClicked(b)})));this.nodes.push(b)},createEmptyItemNode:function(a){a=e.create("div",{"class":"icon-node jimu-float-leading  jimu-main-background"},a);this.nodes.push(a);return a},createCloseBtn:function(){var a;a=e.create("div",{"class":"close"},this.domNode);e.create("div",{"class":"close-inner jimu-main-background"},a);m(a,"click",l.hitch(this,function(){this.hide()}));return a},hide:function(){k=0;f.setStyle(this.domNode,"display",
"none")},show:function(){f.setStyle(this.domNode,"display","block")},onNodeClicked:function(a){this.hide()},_calculateGridParam:function(){var a,d,b,c,e=!1,h=!0;a=f.getContentBox(jimuConfig.mapId);d=Math.min(a.w,a.h)-40;if(360<=d)c=120;else{c=Math.floor(d/3);if(10>c)return null;e=!0;80>c&&(h=!1)}d=Math.floor((a.h-40)/c);b=Math.floor((a.w-40)/c);d=4<d?4:d;d=3>d?3:d;b=3>d?3:4<b?4:b;return{rows:d,cols:b,cellSize:c,iconScaled:e,showLabel:h,position:{top:(a.h-c*d)/2,bottom:(a.h-c*d)/2,left:(a.w-c*b)/2,
right:(a.w-c*b)/2,width:c*b-this.margin*(b-1)/2,height:c*d-this.margin*(d-1)/2,zIndex:111}}}})});