// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./table/FeatureLayerQueryStore jimu/utils".split(" "),function(e,m,q,p,g,f,d,r,h,u,y,n){function w(a,b){if(!a||!a.length)return b||[];if(!b||!b.length)return a;for(var k=[],c=0,l=a.length;c<l;c++)for(var t=a[c],v=0,g=b.length;v<g;v++)if(b[v].name===t.name){k.push(t);break}return k}
f.readLayerInfosObj=function(a){return q.getInstance(a,a.itemInfo)};f.readLayerInfosFromMap=function(a,b,k){var c=new p;q.getInstance(a,a.itemInfo).then(e.hitch(this,function(l){var a=[];b?l.traversalLayerInfosOfWebmap(function(c){a.push(c)}):l.traversal(function(c){a.push(c)});if(k){var v=[],g=l.getMapNotesLayerInfoArray();m.forEach(g,function(c){v.push(c.id);c.traversal(function(c){v.push(c.id)})});a=m.filter(a,function(c){return-1===v.indexOf(c.id)})}l=l.getTableInfoArray();a=a.concat(l);c.resolve(a)}),
e.hitch(this,function(k){console.error(k);c.reject(k)}));return c.promise};f.generateColumnsFromFields=function(a,b,k,c,l,t){function g(c){if(a&&u.isDefined(a.fieldInfos))for(var k=0,l=a.fieldInfos.length;k<l;k++){var b=a.fieldInfos[k];if(b.fieldName===c)return b.format}return null}var d={selectionHandle:{label:"",className:"selection-handle-column",hidden:!1,unhidable:!0,filed:"selection-handle-column",sortable:!1,_cache:{sortable:!1,statistics:!1}}};m.forEach(b,e.hitch(f,function(a,b,v){b="field"+
b;var h=!!a.domain,n="esriFieldTypeDate"===a.type,x=k&&a.name===k,r="esriFieldTypeDouble"===a.type||"esriFieldTypeSingle"===a.type||"esriFieldTypeInteger"===a.type||"esriFieldTypeSmallInteger"===a.type,z="esriFieldTypeString"===a.type;d[b]={label:a.alias||a.name,className:b,hidden:1===v.length?!1:!a.show&&u.isDefined(a.show),unhidable:1===v.length?!1:!a.show&&u.isDefined(a.show)&&a._pk,field:a.name,sortable:!1,_cache:{sortable:!!l,statistics:t&&!h&&r}};z?d[b].formatter=e.hitch(f,f.urlFormatter):n?
d[b].formatter=e.hitch(f,f.dateFormatter,g(a.name)):r&&(d[b].formatter=e.hitch(f,f.numberFormatter,g(a.name)));h?d[b].get=e.hitch(f,function(c,a){return this.getCodeValue(c.domain,a[c.name])},a):x?d[b].get=e.hitch(f,function(c,a,b){return this.getTypeName(b[c.name],a)},a,c):h||n||x||(d[b].get=e.hitch(f,function(c,a,b,k){var l=null;a&&b&&0<b.length&&(b=(b=m.filter(b,e.hitch(f,function(c){return c.name===k[a]})))&&b[0]||null)&&b.domains&&b.domains[c.name]&&b.domains[c.name].codedValues&&(l=this.getCodeValue(b.domains[c.name],
k[c.name]));return(c=null!==l?l:k[c.name])||isFinite(c)?c:""},a,k,c))}));return d};f.getTypeName=function(a,b){return n.fieldFormatter.getTypeName(a,b)};f.getCodeValue=function(a,b){return n.fieldFormatter.getCodedValue(a,b)};f.urlFormatter=function(a){return n.fieldFormatter.getFormattedUrl(a)};f.dateFormatter=function(a,b){return n.fieldFormatter.getFormattedDate(b,a)};f.numberFormatter=function(a,b){return n.fieldFormatter.getFormattedNumber(b,a)};f.readLayerObjectsFromMap=function(a,b,k){var c=
new p,l=[];this.readLayerInfosFromMap(a,b,k).then(e.hitch(this,function(a){m.forEach(a,e.hitch(this,function(c){l.push(c.getLayerObject())}));g(l).then(e.hitch(this,function(a){c.resolve(a)}),e.hitch(this,function(a){c.reject(a);console.error(a)}))}),e.hitch(this,function(a){c.reject(a)}));return c.promise};f.readSupportTableInfoFromLayerInfos=function(a){var b=new p,k=[];m.forEach(a,e.hitch(this,function(c){k.push(c.getSupportTableInfo())}));g(k).then(e.hitch(this,function(c){c=e.clone(c);m.forEach(c,
function(c,b){c.id=a[b].id});b.resolve(c)}),function(c){b.reject(c)});return b.promise};f.readConfigLayerInfosFromMap=function(a,b,k){var c=new p,l=[];this.readLayerInfosFromMap(a,b,k).then(e.hitch(this,function(a){var b=[];m.forEach(a,function(c){l.push(c.getSupportTableInfo())});g(l).then(e.hitch(this,function(k){m.forEach(k,e.hitch(this,function(c,k){c.isSupportedLayer&&(a[k].name=a[k].title,b.push(a[k]))}));c.resolve(b)}),e.hitch(this,function(a){c.reject(a)}))}),e.hitch(this,function(a){c.reject(a)}));
return c.promise};f.getConfigInfosFromLayerInfos=function(a){return m.map(a,function(a){return f.getConfigInfoFromLayerInfo(a)})};f.getConfigInfoFromLayerInfo=function(a){var b={};b.name=a.name||a.title;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()};var k=a.getPopupInfo();k&&!k.description&&(b.layer.fields=m.map(k.fieldInfos,function(c){return{name:c.fieldName,alias:c.label,show:c.visible,format:c.format}}),a=e.getObject("layerObject.fields",!1,a),b.layer.fields=w(b.layer.fields,a),m.some(b.layer.fields,
function(c){return c.show})||(b.layer.fields&&0<b.layer.fields.length?b.layer.fields[0].show=!0:console.warn("We do not get fields info.")));return b};f.generateCacheStore=function(a,b,k,c,l){a=new y({layer:a,objectIds:a._objectIds||null,totalCount:b,batchCount:k,where:c||"1\x3d1",spatialFilter:l});b=new h;return new r(a,b,{})};f.generateMemoryStore=function(a,b){return new d(new h({data:a||[],idProperty:b}))};f.merge=function(a,b,k,c){for(var l=m.map(b,function(c){return c[k]}),t=0,g=a.length;t<
g;t++){var d=l.indexOf(a[t][k]);-1<d&&c(a[t],b[d])}};f.syncOrderWith=function(a,b,k){function c(c,a){return m.map(c,function(c){return c[a]})}if(!e.isArray(b)||!k)return a;for(var l=c(a,k),g=[],d=0,f=b.length;d<f;d++){var h=l.indexOf(b[d][k]);-1<h&&(g=g.concat(a.splice(h,1)),l=c(a,k))}return g.concat(a)}})},"dojo/store/Observable":function(){define(["../_base/kernel","../_base/lang","../when","../_base/array"],function(e,m,q,p){e=function(g){function f(d,f){var h=g[d];h&&(g[d]=function(a){var b;"put"===
d&&(b=g.getIdentity(a));if(u)return h.apply(this,arguments);u=!0;try{var k=h.apply(this,arguments);q(k,function(c){f("object"==typeof c&&c||a,b)});return k}finally{u=!1}})}var d=[],e=0;g=m.delegate(g);g.notify=function(g,f){e++;for(var h=d.slice(),a=0,b=h.length;a<b;a++)h[a](g,f)};var h=g.query;g.query=function(f,u){u=u||{};var r=h.apply(this,arguments);if(r&&r.forEach){var a=m.mixin({},u);delete a.start;delete a.count;var b=g.queryEngine&&g.queryEngine(f,a),k=e,c=[],l;r.observe=function(a,f){1==
c.push(a)&&d.push(l=function(a,l){q(r,function(d){var t=d.length!=u.count,h,v;if(++k!=e)throw Error("Query is out of date, you must observe() the query prior to any data modifications");var r,m=-1,n=-1;if(void 0!==l){var x=[].concat(d);b&&!a&&(x=b(d));h=0;for(v=d.length;h<v;h++){var q=d[h];if(g.getIdentity(q)==l&&!(0>x.indexOf(q))){r=q;m=h;!b&&a||d.splice(h,1);break}}}b?a&&(b.matches?b.matches(a):b([a]).length)&&(h=-1<m?m:d.length,d.splice(h,0,a),n=p.indexOf(b(d),a),d.splice(h,1),u.start&&0==n||!t&&
n==d.length?n=-1:d.splice(n,0,a)):a&&(void 0!==l?n=m:u.start||(n=g.defaultIndex||0,d.splice(n,0,a)));if((-1<m||-1<n)&&(f||!b||m!=n))for(t=c.slice(),h=0;d=t[h];h++)d(a||r,m,n)})});var t={};t.remove=t.cancel=function(){var b=p.indexOf(c,a);-1<b&&(c.splice(b,1),c.length||d.splice(p.indexOf(d,l),1))};return t}}return r};var u;f("put",function(d,f){g.notify(d,f)});f("add",function(d){g.notify(d)});f("remove",function(d){g.notify(void 0,d)});return g};m.setObject("dojo.store.Observable",e);return e})},
"dojo/store/Cache":function(){define(["../_base/lang","../when"],function(e,m){var q=function(p,g,f){f=f||{};return e.delegate(p,{query:function(d,e){var h=p.query(d,e);h.forEach(function(d){f.isLoaded&&!f.isLoaded(d)||g.put(d)});return h},queryEngine:p.queryEngine||g.queryEngine,get:function(d,f){return m(g.get(d),function(h){return h||m(p.get(d,f),function(f){f&&g.put(f,{id:d});return f})})},add:function(d,f){return m(p.add(d,f),function(h){g.add(h&&"object"==typeof h?h:d,f);return h})},put:function(d,
f){g.remove(f&&f.id||this.getIdentity(d));return m(p.put(d,f),function(h){g.put(h&&"object"==typeof h?h:d,f);return h})},remove:function(d,f){return m(p.remove(d,f),function(h){return g.remove(d,f)})},evict:function(d){return g.remove(d)}})};e.setObject("dojo.store.Cache",q);return q})},"widgets/AttributeTable/table/FeatureLayerQueryStore":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/tasks/query esri/tasks/QueryTask ./FeatureLayerQueryResult".split(" "),function(e,m,
q,p,g,f){return e(null,{queryUrl:"",idProperty:"id",data:null,_entityData:null,constructor:function(d){e.safeMixin(this,d);this.data=[];this._entityData=[];this.layer=d.layer;this.objectIds=d.objectIds;this.where=d.where;this.orderByFields=d.orderByFields;this.totalCount=d.totalCount;this.batchCount=d.batchCount||25;this.idProperty=this.layer.objectIdField;this.spatialFilter=d.spatialFilter;this.layer&&this.layer.url&&(this.queryTask=new g(this.layer.url))},get:function(d){return this.data[d]},getIdentity:function(d){return d[this.idProperty]},
query:function(d,g){var h=new p,e=g&&g.start||0,r=this.batchCount,n=null;"function"===typeof d?n=d(this._entityData):"[object Array]"===Object.prototype.toString.call(d)&&(n=d);this.objectIds?(n=n?n:this.objectIds,h.objectIds=n.length>=e+this.batchCount?n.slice(e,e+r):n.slice(e)):(n&&0<n.length?h.objectIds=n.length>=e+this.batchCount?n.slice(e,e+r):n.slice(e):(h.start=e,h.num=r,h.where=this.where,h.geometry=this.spatialFilter,h.spatialRelationship=p.SPATIAL_REL_INTERSECTS),(e=g.sort)&&0<e.length&&
(e=q.map(e,function(a){return a.attribute+" "+(a.descending?"DESC":"ASC")}),h.orderByFields=e));h.returnGeometry="esriGeometryPoint"===this.layer.geometryType;h.outFields=["*"];var w=this.totalCount,e=null,e=!h.where;if(!(h.objectIds&&0<h.objectIds.length)&&e)return new f([]);e=this.queryTask?this.queryTask.execute(h):this.layer.queryFeatures(h);e.total=e.then(m.hitch(this,function(a){var b=0,k=this.layer.objectIdField;if(this.objectIds){if(!k)for(b=0;b<a.fields.length;b++)if("esriFieldTypeOID"===
a.fields[b].type){k=a.fields[b].name;break}for(var c={},b=0;b<a.features.length;b++)c[a.features[b].attributes[k]]=a.features[b];a.features=q.map(h.objectIds,function(a){return c[a]})}for(b=0;b<a.features.length;b++)if(a.features[b]){var l=a.features[b];a.features[b]=m.mixin(m.clone(l.attributes),{geometry:l.geometry});this.data[a.features[b][k]]=a.features[b];this._entityData.push(a.features[b])}a=a.features;return w}),function(){console.log("FeatureLayerQueryStore queryFeatures failed.");return 0});
return new f(e)}})})},"widgets/AttributeTable/table/FeatureLayerQueryResult":function(){define("esri/main dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/DeferredList dojo/_base/array".split(" "),function(e,m,q,p){var g=function(f){function d(d){f[d]||(f[d]=function(){var e=arguments;return p.when(f,function(f){Array.prototype.unshift.call(e,f.features||f);return g(q[d].apply(q,e))})})}if(!f)return f;f.then&&(f=m.delegate(f));f.total||(f.total=p.when(f,function(d){return e._isDefined(d.total)?
d.total:d.length||0}));d("forEach");d("filter");d("map");d("some");d("every");return f};return g})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv class\x3d"instruction"\x3e\r\n    \x3cp\x3e${nls.instruction}\x3c/p\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"table-options jimu-ellipsis"\x3e\r\n    \x3cul\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"exportcsv" checked\r\n        data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"expand" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.expand}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"filterByMapExtent" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.filterByExtent}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n    \x3c/ul\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:14px; width: 100%; height: 100%; position: relative; color: #596679;}.jimu-widget-attributetable-setting .instruction{font-size: 12px; margin-bottom: 10px;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; height: 396px;}.jimu-widget-attributetable-setting .table-options ul{list-style-type: none; padding: 0;}.jimu-widget-attributetable-setting .jimu-checkbox{margin-right: 20px;}.jimu-widget-attributetable-setting .disable-checkbox{color: #e5e5e5;}",
"*now":function(e){e(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])},"*noref":1}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/query jimu/dijit/Popup jimu/dijit/Message jimu/dijit/CheckBox jimu/dijit/LoadingShelter ../utils".split(" "),function(e,m,q,p,g,f,d,r,h,u,y,n,w,a,b){return e([q,m],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,_allLayerFields:null,_layerInfos:null,_tableInfos:null,_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,
_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new p({fields:[{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"},{name:"label",title:this.nls.label,width:"60%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"20%",actions:["edit"],"class":"symbol"},{name:"showAttachments",title:"",type:"checkbox",hidden:!0}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);f.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.shelter=new a({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();
b.readLayerInfosObj(this.map).then(g.hitch(this,function(a){this.own(a.on("layerInfosChanged",g.hitch(this,this.onLayerInfosChanged)));this.own(r(this.displayFieldsTable,"actions-edit",g.hitch(this,this.editFieldsClick)));this.own(r(this.displayFieldsTable,"row-click",g.hitch(this,this._verifiedOnShowClick)));this.setConfig(this.config)}))},editFieldsClick:function(a){var c=u(".action-item-parent",a);if(c&&c.length)if(c=this.displayFieldsTable.getRowData(a),c.show){var b=parseInt(c.index,10);this.shelter.show();
this._getLayerFields(b).then(g.hitch(this,function(c){this.openFieldsDialog(a,c,b)}),g.hitch(this,function(a){console.error(a)})).always(g.hitch(this,function(){this.shelter.hide()}))}else var k=new n({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:g.hitch(this,function(){k.close()})}]})},_verifiedOnShowClick:function(a){var c=this.displayFieldsTable.getRowData(a),b=parseInt(c.index,10),k=null,k=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[b]:
this._layerInfos[b],b=-1<this._unSpportQueryCampsite.layerNames.indexOf(k.name||k.title);c.show&&b&&(new n({message:this.nls.unsupportQueryWarning}),c.show=!1,this.displayFieldsTable.editRow(a,c))},_getLayerFields:function(a){return this._layerInfos[a].getLayerObject().then(g.hitch(this,function(c){var k=this._allLayerFields[a];c=d.map(c.fields,function(a){return{name:a.name,alias:a.alias,show:!0}});b.merge(c,k,"name",function(a,c){g.mixin(a,c)});return c=b.syncOrderWith(c,k,"name")}))},openFieldsDialog:function(a,
c,b){var k=!1,d=this._layerInfos[b];(d=d&&d.layerObject)&&(k=d.hasAttachments&&d.objectIdField);var d=f.create("div"),l=this._createFieldsTable(c,b);f.place(l.domNode,d);var e=null;k&&(e=new w({label:this.nls.showAttachments,style:"margin-top:10px;"}),c=this.displayFieldsTable.getRowData(a),e.setValue(c.showAttachments),e.placeAt(d));this.currentFieldTable=l;c=600;e&&(c=640);var h=new y({titleLabel:this.nls.configureLayerFields,width:640,maxHeight:c,autoHeight:!0,content:d,buttons:[{label:this.nls.ok,
onClick:g.hitch(this,function(){this._allLayerFields[b]=l.getData();var c=e?e.getValue():!1;this.displayFieldsTable.editRow(a,{showAttachments:c});h.close();h=null})},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],onClick:g.hitch(this,function(){h.close();h=null})}],onClose:function(){h=null}});l.startup()},_createFieldsTable:function(a){for(var c=null,b={fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show",onChange:g.hitch(this,function(a){var b=c.getData();
!d.some(b,g.hitch(this,function(a){return a.show}))&&(new n({message:this.nls.fieldCheckWarning}),b=c.getRowData(a))&&(b.show=!0,c.editRow(a,b))})},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}},c=new p(b),b=0;b<a.length;b++)a[b].show=void 0===a[b].show?!0:!!a[b].show,
c.addRow(a[b]);return c},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this._processTableData().then(g.hitch(this,function(a){this._init(a);this.shelter.hide()}),g.hitch(this,function(a){new n({message:a.message||a})}))},onLayerInfosChanged:function(a,c,b){"added"===c&&b&&a&&b.getSupportTableInfo().then(g.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?this._delayedLayerInfos.push(b):this._layerInfos&&0<this._layerInfos.length&&
!this._getLayerInfoById(b.id)&&(this._delayedLayerInfosAfterInit.push(b),this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var c=this._layerInfos.length,d=0;d<a.length;d++){var k=b.getConfigInfoFromLayerInfo(a[d]);this.displayFieldsTable.addRow({label:k.name||k.title,url:k.layer.url,index:""+(c+d),show:k.show});this._allLayerFields.push(k.layer.fields);this._layerInfos.push(a[d])}},_processDelayedLayerInfos:function(){0<
this._delayedLayerInfos.length&&(d.forEach(this._delayedLayerInfos,g.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new h;b.readConfigLayerInfosFromMap(this.map,!0,!0).then(g.hitch(this,function(c){this._layerInfos=c;this._processDelayedLayerInfos();b.readSupportTableInfoFromLayerInfos(this._layerInfos).then(g.hitch(this,function(d){this._tableInfos=d;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?
(d=b.getConfigInfosFromLayerInfos(this._layerInfos),b.merge(d,this.config.layerInfos,"id",g.hitch(this,function(a,c){a.show=c.show;a.showAttachments=c.showAttachments;a.layer.url=c.layer.url;g.getObject("layer.fields.length",!1,a)&&g.getObject("layer.fields.length",!1,c)?(b.merge(a.layer.fields,c.layer.fields,"name",function(a,c){g.mixin(a,c)}),a.layer.fields=b.syncOrderWith(a.layer.fields,c.layer.fields,"name")):a.layer.fields=c.layer.fields})),this.config.layerInfos=d,this._unSpportQueryCampsite.fromConfig=
!0,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this.config.layerInfos),a.resolve(d)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(b.getConfigInfosFromLayerInfos(c)))}),function(c){console.error(c);a.reject(c)})}),g.hitch(this,function(c){console.error(c);a.reject(c)}));return a},_getUnsupportQueryLayerNames:function(a){var c=[];d.forEach(a,g.hitch(this,function(a){var b=
this._getSupportTableInfoById(a.id);b&&!b.isSupportQuery&&c.push(a.name||a.title)}));return c},_init:function(a){for(var c=[],b=0;b<a.length;b++){var d=a[b].show&&this._getSupportTableInfoById(a[b].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[b].name||a[b].title,url:a[b].layer.url,index:""+b,show:d,showAttachments:!!a[b].showAttachments});this._allLayerFields.push(a[b].layer.fields);this._unSpportQueryCampsite.fromConfig&&(d=(d=this._unSpportQueryCampsite.layerNames)&&-1<d.indexOf(a[b].name||
a[b].title),a[b].show&&d&&c.push(a[b].name||a[b].title))}this._unSpportQueryCampsite.fromConfig&&0<c.length&&new n({message:this.nls.unsupportQueryLayers+"\x3cbr\x3e\x3cbr\x3e"+c.toString()});this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check();this.config.initiallyExpand?this.expand.check():this.expand.uncheck();this._canUseOpenAtStart()&&(this.openAtStart?this.expand.check():this.expand.uncheck(),this.expand.status=!1,f.addClass(this.expand.domNode,"disable-checkbox"));this.config.filterByMapExtent?
this.filterByMapExtent.check():this.filterByMapExtent.uncheck()},_canUseOpenAtStart:function(){return this.closeable||!this.isOnScreen},_getLayerInfoById:function(a){for(var b=0,d=this._layerInfos.length;b<d;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,d=this._tableInfos.length;b<d;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){var a=this.displayFieldsTable.getData(),b=[],f=a.length;if(this.config&&
this.config.layerInfos&&0<this.config.layerInfos.length)d.forEach(a,g.hitch(this,function(c,d){var f=this.config.layerInfos[d],e={};e.name=f.name||f.title;e.id=f.id;e.layer={};e.layer.url=a[d].url;e.layer.fields=this._allLayerFields[d];e.show=a[d].show;e.showAttachments=a[d].showAttachments;b.push(e)}));else for(var e=0;e<f;e++){var h={};h.name=this._layerInfos[e].name||this._layerInfos[e].title;h.id=this._layerInfos[e].id;h.layer={};h.layer.url=a[e].url;h.layer.fields=this._allLayerFields[e];h.show=
a[e].show;h.showAttachments=a[e].showAttachments;b.push(h)}this.config.layerInfos=b;this.config.hideExportButton=!this.exportcsv.getValue();this.config.filterByMapExtent=this.filterByMapExtent.getValue();this._canUseOpenAtStart()||(this.config.initiallyExpand=this.expand.getValue());return this.config}})});